; ---------------------------------------------------------------------------
SCR_POS		= 000Ch

;tLevelAttr	struc ;	(sizeof=0xD)
;PlayerStarPosY:	.DB	?
;PlayerStarPosX:	.DB	?
;Guard1StartPosY:.DB	?
;Guard1StartPosX:.DB	?
;Guard2StartPosY:.DB	?
;Guard2StartPosX:.DB	?
;Guard3StartPosY:.DB	?
;Guard3StartPosX:.DB	?
;Guard4StartPosY:.DB	?
;Guard4StartPosX:.DB	?
;GuardCount:	.DB	?
;ExitPosY:	.DB	?
;ExitPosX:	.DB	?
;tLevelAttr	ends


;
; +-------------------------------------------------------------------------+
; |	This file is generated by The Interactive Disassembler (IDA)	    |
; |	Copyright (c) 2007 by DataRescue sa/nv,	<ida@datarescue.com>	    |
; | Licensed to: Mach EDV Dienstleistungen, Jan	Mach, 1	user, adv, 11/2007  |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	C88352DCF9312708C558C3426673627C

; ---------------------------------------------------------------------------
; File Name   :	D:\fpga\ds_fpga\2\klad\KLAD.Rom
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 3352h Loaded length: 3352h

; Processor	  : z80	[]
; Target assembler: Zilog Macro	Assembler

; ===========================================================================

; Segment type:	Pure code


; ---------------------------------------------------------------------------

	.ORG	0100h
	LD	A, 0
loc_0100:
	ld	(vLevel), A
	call	CLEAR_Map
	CALL	OUT_Map
	CALL	prtmap

	RST	10h
	LD	A, 0Ah
	RST	08h
	LD	A, 0Dh
	RST	08h
	LD	A, 0Ah
	RST	08h
	LD	A, 0Dh
	RST	08h
	ld	A, (vLevel)
	INC	A
	CP	19
	JR	NZ, loc_0100
	RST	00h


prtmap:
	ld	hl,  MapLine0
	LD	B, 24
loc_9743:
	PUSH	BC
	LD	B, 64
loc_9742:
	LD	A, (hl)
	INC	hl
	CP	1Fh
	JR	NC, loc_9744
	ADD	A, 60h
loc_9744:
	RST	08h

	djnz	loc_9742

	LD	A, 0Ah
	RST	08h
	LD	A, 0Dh
	RST	08h

	POP	BC
	djnz	loc_9743
	ret



	ld	sp, 0FFh
;		jp	OUT_MainScreen
	LD	A, 01h	; 8x16, Font 1bit, Scale x2
	OUT	(0F7h), A

OUT_MainScreen:				; CODE XREF: ROM:0003j
	ld	hl, byte_1612
	call	PrintString
	call	0010h
	jp	GAME_RESTART

; ---------------------------------------------------------------------------
PrintString:
	LD	A, (HL)
	OR	A
	RET	Z
	CALL	0008h
	INC	HL
	JP	PrintString

; =============== S U B	R O U T	I N E =======================================
OUT_Map:
;		ld	c, 1Fh
		call	0FD00h
		ld	hl, Levels
		xor	a
		ld	a, (vLevel)
		rla
		ld	e, a
		ld	d, 0
		add	hl, de
		ld	a, (hl)
		ld	(SrcMapsOffset), a
		inc	hl
		ld	a, (hl)
		ld	(SrcMapsOffset+1), a
		ld	hl, MapLine0
		ld	(DstMapOffset),	hl

loc_120:
		ld	hl, (SrcMapsOffset)
		ld	a, (hl)
		or	a
		ret	z
		call	CONVERT_CHAR
		ld	a, (CONVERTED_CHAR)
		ld	(MapCHAR), a
		inc	hl
		ld	a, (hl)
		ld	(MapStartY), a
		inc	hl
		ld	a, (hl)
		ld	(MapEndY), a
		inc	hl
		ld	a, (hl)
		ld	(MapStartX), a
		inc	hl
		ld	a, (hl)
		ld	(MapEndX), a
		inc	hl
		ld	(SrcMapsOffset), hl

loc_144:				; CODE XREF: OUT_Map???+97j
		ld	a, (MapStartY)
		ld	b, a
		ld	a, (MapStartX)
		ld	c, a
		call	MapDstADDR_BCtoHL
		ld	(MapDstADDR_tmp), hl
		ld	a, (MapStartY)
		ld	d, a
		ld	a, (MapEndY)
		sub	d
		ld	(MapCHARCntY), a
		ld	a, (MapStartX)
		ld	d, a
		ld	a, (MapEndX)
		sub	d
		ld	(MapCHARCntX), a
		ld	hl, (MapDstADDR_tmp)
		ex	de, hl
		ld	a, (MapStartX)
		ld	c, a
		ld	a, (MapStartY)
		ld	b, a

loc_174:				; CODE XREF: OUT_Map???+86j
		ld	a, (MapCHAR)
		ld	(de), a
		call	ToScreen_A_BC_XY_
		inc	de
		inc	c
		ld	a, (MapCHARCntX)
		dec	a
		ld	(MapCHARCntX), a
		cp	0FFh
		jp	nz, loc_174
		ld	a, (MapCHARCntY)
		or	a
		jp	z, loc_120
		ld	a, (MapStartY)
		inc	a
		ld	(MapStartY), a
		jp	loc_144
; End of function OUT_Map???

; ---------------------------------------------------------------------------
CONVERTED_CHAR:	.DB	0

; =============== S U B	R O U T	I N E =======================================


CONVERT_CHAR:				; CODE XREF: OUT_Map???+26p
					; ToScreen_A_BC_XY_+3p
		push	af
		push	hl
		push	de
		ld	e, a
		ld	d, 0
		ld	hl, CHARS
		add	hl, de
		ld	a, (hl)
		ld	(CONVERTED_CHAR), a
		pop	de
		pop	hl
		pop	af
		ret
; End of function CONVERT_CHAR

; ---------------------------------------------------------------------------
CHR_SPACE		= 00h
CHR_STONE		= 01h
CHR_LAD			= 02h
CHR_DOORLEFT		= 03h
CHR_DOORRIGHT		= 04h
CHR_WATER		= 05h
CHR_BRIDGE		= 06h
CHR_GOLD0		= 07h
CHR_GOLD1		= 08h
CHR_DOORLEFTKEY		= 09h
CHR_DOORRIGHTKEY	= 0Ah
CHR_BRICK		= 0Bh
CHR_BRICK1		= 0Ch
CHR_BRICK2		= 0Dh
CHR_STONESPACE		= 0Eh
CHR_BRICK3		= 0Fh
CHR_BRICK4		= 10h
CHR_DOOR_OPEN		= 11h
CHR_APPLE		= 12h
CHR_PLAYER		= 13h
CHR_GUARD		= 14h
;CHR_STONEKILL	= '*'


CHARS:		.DB	' '	; 00
		.DB	'X'	; 01 X
		.DB	'#'	; 02 #
		.DB	']'	; 03 ]
		.DB	'['	; 04 [
		.DB	'~'	; 05 ^
		.DB	'-'	; 06	---
		.DB	'&'	; 07	___
		.DB	'^'	; 08	___
		.DB	']'	; 09 ]
		.DB	'['	; 0A [
		.DB	'%'	; 0B %
		.DB	':'	; 0C :
		.DB	'.'	; 0D .
		.DB	' '	; 0E 
		.DB	'.'	; 0F .
		.DB	':'	; 10 :
		.DB	'|'	; 11	{
		.DB	'@'	; 12	Apple
		.DB	09h	; 13	Man
		.DB	0Bh	; 14	Guard
		.DB	'-'	; 15 -
		.DB	51h	; 16 Q
		.DB	4Fh	; 17 @
		.DB	26h	; 18 &
		.DB	2Ah	; 19 *
		.DB	3Dh	; 1A =
		.DB	2Bh	; 1B +
		.DB	3Eh	; 1C >
		.DB	3Ch	; 1D <

Levels:		.DW	Level0
		.DW	Level1
		.DW	Level2
		.DW	Level3
		.DW	Level4
		.DW	Level5
		.DW	Level6
		.DW	Level7
		.DW	Level8
		.DW	Level9
		.DW	Level10
		.DW	Level11
		.DW	Level12
		.DW	Level13
		.DW	Level14
		.DW	Level15
		.DW	Level16
		.DW	Level17
		.DW	Level18
		.DW	0
;		.DW	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
;		.DW	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
vLevel:		.DB	0

SrcMapsOffset:	.DW	0

DstMapOffset:	.DW	MapLine0
MapCHAR:	.DB	2
MapStartY:	.DB	5
MapEndY:	.DB	5
MapStartX:	.DB	0Ah
MapEndX:	.DB	0Bh
MapDstADDR_tmp:	.DW	0
MapCHARCntY:	.DB	0
MapCHARCntX:	.DB	0FFh

; =============== S U B	R O U T	I N E =======================================


CLEAR_Map:				; CODE XREF: GAME_RESTART+4p
		ld	hl, MapLine0
		ld	de, MapLine0 + 1664

loc_894:				; CODE XREF: CLEAR_Map+Dj
		xor	a
		ld	(hl), a
		inc	hl
		ld	a, e
		sub	l
		ld	a, d
		sbc	a, h
		jp	nc, loc_894
		ret
; End of function CLEAR_Map


; =============== S U B	R O U T	I N E =======================================


COPY_LevelAttrib:			; CODE XREF: GAME_RESTART+Ap
		ld	hl, (SrcMapsOffset)
		inc	hl
		ld	de, LevelAttrib
		ld	b, 0Dh

loc_8A8:				; CODE XREF: COPY_LevelAttrib+Ej
		ld	a, (hl)
		ld	(de), a
		inc	hl
		inc	de
		dec	b
		jp	nz, loc_8A8
		ret
; End of function COPY_LevelAttrib

; ---------------------------------------------------------------------------
;LevelAttrib:	tLevelAttr <0Fh, 4, 1, 2Eh, 0, 0, 0, 0,	0, 0, 0, 1, 35h>
LevelAttrib:
;	.DB	0Fh, 4, 1, 2Eh, 0, 0, 0, 0,	0, 0, 0, 1, 35h
PlayerStarPosY:	.DB	0
PlayerStarPosX:	.DB	0
Guard1StartPosY:.DB	0
Guard1StartPosX:.DB	0
Guard2StartPosY:.DB	0
Guard2StartPosX:.DB	0
Guard3StartPosY:.DB	0
Guard3StartPosX:.DB	0
Guard4StartPosY:.DB	0
Guard4StartPosX:.DB	0
GuardCount:	.DB	0
ExitPosY:	.DB	0
ExitPosX:	.DB	0

; =============== S U B	R O U T	I N E =======================================


MapDstADDR_BCtoHL:			; CODE XREF: OUT_Map???+4Cp
					; PlayerStep+8p ...
		push	af
		push	de
		ld	a, b
		cp	24
		jp	c, loc_8C8
		ld	b, 24

loc_8C8:				; CODE XREF: MapDstADDR_BCtoHL+5j
		ld	a, c
		cp	63
		jp	c, loc_8D0
		ld	c, 63

loc_8D0:				; CODE XREF: MapDstADDR_BCtoHL+Dj
		xor	a
		ld	de, 0
		ld	a, b
		rra
		ld	d, a
		ld	a, e
		rra
		ld	e, a
		ld	a, d
		rra
		ld	d, a
		ld	a, e
		rra
		add	a, c
		ld	e, a
		ld	a, d
		adc	a, 0
		ld	hl, (DstMapOffset)
		add	hl, de
		pop	de
		pop	af
		ret
; End of function MapDstADDR_BCtoHL


; =============== S U B	R O U T	I N E =======================================


PlayerStep:				; CODE XREF: GAME_RESTART+25p
		ld	a, (PlayerPosY)
		ld	b, a
		ld	a, (PlayerPosX)
		ld	c, a
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		cp	2	; CHR_LAD
		jp	z, loc_961
		inc	b
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		or	a	; CHR_SPACE
		jp	z, loc_919
		cp	7	; CHR_GOLD0
		jp	z, loc_919
		cp	8	; CHR_GOLD1
		jp	z, loc_919
		cp	5	; CHR_WATER
		jp	z, loc_919
		cp	0Eh	; CHR_STONESPACE
		jp	c, loc_953

loc_919:				; CODE XREF: PlayerStep+17j
					; PlayerStep+1Cj ...
		dec	b
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		call	ToScreen_A_BC_XY_
		inc	b
		ld	a, (byte_AD6)
		inc	a
		and	3
		jp	nz, loc_92C
		dec	b

loc_92C:				; CODE XREF: PlayerStep+3Dj
		ld	(byte_AD6), a
		ld	a, b
		ld	(PlayerPosY), a
		ld	a, 13h	; CHR_MAN
		call	ToScreen_A_BC_XY_
		ld	(byte_AD7), a
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		cp	7	; CHR_GOLD0
		jp	nz, loc_946
		ld	(hl), 0

loc_946:				; CODE XREF: PlayerStep+56j
		cp	8	; CHR_GOLD1
		ret	nz
		ld	(hl), 12h	; CHR_APPLE
		ld	a, (vKEYCnt)
		inc	a
		ld	(vKEYCnt), a
		ret
; ---------------------------------------------------------------------------

loc_953:				; CODE XREF: PlayerStep+2Bj
		ld	a, (byte_AD7)
		or	a
		jp	z, loc_960
		ld	a, (hl)
		cp	6	; CHR_BRIDGE
		jp	z, loc_919

loc_960:				; CODE XREF: PlayerStep+6Cj
		dec	b

loc_961:				; CODE XREF: PlayerStep+Ej
		xor	a
		ld	(byte_AD7), a

		ld	a, (KeyPressed)
		cp	'a'
		jp	z, MoveLeft
		cp	'd'
		jp	z, MoveRight
		cp	'w'
		jp	z, MoveUp
		cp	's'
		jp	z, MoveDown

		jp	locret_AD3
; ---------------------------------------------------------------------------

MoveLeft:				; CODE XREF: PlayerStep+7Fj
		dec	c
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		or	a	; CHR_SPACE
		jp	z, loc_9D0
		cp	2	; CHR_LAD
		jp	z, loc_9D0
		cp	6	; CHR_BRIDGE
		jp	z, loc_9D0
		cp	3	; CHR_DOORLEFT
		jp	nz, loc_99C
		ld	(hl), 11h	; CHR_DOOR_OPEN
		jp	loc_9D0
; ---------------------------------------------------------------------------

loc_99C:				; CODE XREF: PlayerStep+A9j
		cp	5	; CHR_WATER
		jp	z, loc_9D0
		cp	7	; CHR_GOLD0
		jp	nz, loc_9AB
		ld	(hl), 0	; CHR_SPACE
		jp	loc_9D0
; ---------------------------------------------------------------------------

loc_9AB:				; CODE XREF: PlayerStep+B8j
		cp	8	; CHR_GOLD1
		jp	nz, loc_9B6
		call	KEY_INC
		jp	loc_9D0
; ---------------------------------------------------------------------------

loc_9B6:				; CODE XREF: PlayerStep+C2j
		cp	9	; CHR_DOORLEFTKEY
		jp	nz, loc_9CB
		ld	a, (vKEYCnt)
		or	a
		jp	z, locret_AD3
		dec	a
		ld	(vKEYCnt), a
		ld	(hl), 11h	; CHR_DOOR_OPEN
		jp	loc_9D0
; ---------------------------------------------------------------------------

loc_9CB:				; CODE XREF: PlayerStep+CDj
		cp	0Eh	; CHR_STONESPACE
		jp	c, locret_AD3

loc_9D0:				; CODE XREF: PlayerStep+9Aj
					; PlayerStep+9Fj ...
		inc	c
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		call	ToScreen_A_BC_XY_
		dec	c
		ld	a, 13h	; CHR_MAN
		call	ToScreen_A_BC_XY_
		ld	a, c
		ld	(PlayerPosX), a
		ret
; ---------------------------------------------------------------------------

MoveRight:				; CODE XREF: PlayerStep+84j
		inc	c
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		or	a	; CHR_SPACE
		jp	z, loc_A34
		cp	2	; CHR_LAD
		jp	z, loc_A34
		cp	6	; CHR_BRIDGE
		jp	z, loc_A34
		cp	4	; CHR_DOORRIGHT
		jp	nz, loc_A00
		ld	(hl), 11h	; CHR_DOOR_OPEN
		jp	loc_A34
; ---------------------------------------------------------------------------

loc_A00:				; CODE XREF: PlayerStep+10Dj
		cp	5	; CHR_WATER
		jp	z, loc_A34
		cp	7	; CHR_GOLD0
		jp	nz, loc_A0F
		ld	(hl), 0	; CHR_SPACE
		jp	loc_A34
; ---------------------------------------------------------------------------

loc_A0F:				; CODE XREF: PlayerStep+11Cj
		cp	8	; CHR_GOLD1
		jp	nz, loc_A1A
		call	KEY_INC
		jp	loc_A34
; ---------------------------------------------------------------------------

loc_A1A:				; CODE XREF: PlayerStep+126j
		cp	0Ah	; CHR_DOORRIGHTKEY
		jp	nz, loc_A2F
		ld	a, (vKEYCnt)
		or	a
		jp	z, locret_AD3
		dec	a
		ld	(vKEYCnt), a
		ld	(hl), 11h	; CHR_DOOR_OPEN
		jp	loc_A34
; ---------------------------------------------------------------------------

loc_A2F:				; CODE XREF: PlayerStep+131j
		cp	0Eh	; CHR_STONESPACE
		jp	c, locret_AD3

loc_A34:				; CODE XREF: PlayerStep+FEj
					; PlayerStep+103j ...
		dec	c
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		call	ToScreen_A_BC_XY_
		inc	c
		ld	a, 13h	; CHR_MAN
		call	ToScreen_A_BC_XY_
		ld	a, c
		ld	(PlayerPosX), a
		jp	locret_AD3
; ---------------------------------------------------------------------------

MoveUp:					; CODE XREF: PlayerStep+89j
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		cp	2	; CHR_LAD
		jp	nz, locret_AD3
		dec	b
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		or	a	; CHR_SPACE
		jp	z, loc_A7F
		cp	2	; CHR_LAD
		jp	z, loc_A7F
		cp	5	; CHR_WATER
		jp	z, loc_A7F
		cp	7	; CHR_GOLD0
		jp	nz, loc_A6F
		ld	(hl), 0	; CHR_SPACE
		jp	loc_A7F
; ---------------------------------------------------------------------------

loc_A6F:				; CODE XREF: PlayerStep+17Cj
		cp	8	; CHR_GOLD1
		jp	nz, loc_A7A
		call	KEY_INC
		jp	loc_A7F
; ---------------------------------------------------------------------------

loc_A7A:				; CODE XREF: PlayerStep+186j
		cp	0Eh	; CHR_STONESPACE
		jp	c, locret_AD3

loc_A7F:				; CODE XREF: PlayerStep+16Dj
					; PlayerStep+172j ...
		inc	b
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		call	ToScreen_A_BC_XY_
		dec	b
		ld	a, 13h	; CHR_MAN
		call	ToScreen_A_BC_XY_
		ld	a, b
		ld	(PlayerPosY), a
		jp	locret_AD3
; ---------------------------------------------------------------------------

MoveDown:				; CODE XREF: PlayerStep+8Ej
		inc	b
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		or	a	; CHR_SPACE
		jp	z, loc_AC1
		cp	2	; CHR_LAD
		jp	z, loc_AC1
		cp	5	; CHR_WATER
		jp	z, loc_AC1
		cp	7	; CHR_GOLD0
		jp	nz, loc_AB1
		ld	(hl), 0	; CHR_SPACE
		jp	loc_AC1
; ---------------------------------------------------------------------------

loc_AB1:				; CODE XREF: PlayerStep+1BEj
		cp	8	; CHR_GOLD1
		jp	nz, loc_ABC
		call	KEY_INC
		jp	loc_AC1
; ---------------------------------------------------------------------------

loc_ABC:				; CODE XREF: PlayerStep+1C8j
		cp	0Eh	; CHR_STONESPACE
		jp	c, locret_AD3

loc_AC1:				; CODE XREF: PlayerStep+1AFj
					; PlayerStep+1B4j ...
		dec	b
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		call	ToScreen_A_BC_XY_
		inc	b
		ld	a, 13h	; CHR_MAN
		call	ToScreen_A_BC_XY_
		ld	a, b
		ld	(PlayerPosY), a

locret_AD3:				; CODE XREF: PlayerStep+91j
					; PlayerStep+D4j ...
		ret

; ---------------------------------------------------------------------------
PlayerPosY:	.DB	15h
PlayerPosX:	.DB	8
byte_AD6:	.DB	1
byte_AD7:	.DB	0
KeyPressed:	.DB	3Ah
vKEYCnt:	.DB	0

; =============== S U B	R O U T	I N E =======================================
GAME_RESTART:
	xor	a
	ld	(vKEYCnt), a
	call	CLEAR_Map
	call	OUT_Map
	call	COPY_LevelAttrib
;	ld	a, (LevelAttrib.PlayerStarPosY)
	ld	a, (PlayerStarPosY)
	ld	(PlayerPosY), a
;	ld	a, (LevelAttrib.PlayerStarPosX)
	ld	a, (PlayerStarPosX)
	ld	(PlayerPosX), a
	call	Clear_ShutBuf
	call	COPY_GuardAttrib

GAME_LOOP:
	call	0018h
	LD	A, 0FFh
	jr	z, loc_416
	call	0010h
loc_416:
	ld	(KeyPressed), a

	call	PlayerStep
	call	GuardStep
	call	PlayerVsGuard
	call	GameSpeed
	call	PlayerShut
	call	PlayerShut
	call	CHECK_LevelEnd
	ld	a, (vLevelChange)
	or	a
	jp	nz, GAME_RESTART
	ld	a, (PlayerPosY)
	ld	b, a
	ld	a, (PlayerPosX)
	ld	c, a
	call	MapDstADDR_BCtoHL
	ld	a, (hl)
	cp	5	; CHR_WATER
	jp	z, GAME_RESTART
	ld	a, b
	cp	24	; CHR_
	jp	nc, GAME_RESTART
	jp	GAME_LOOP

; ---------------------------------------------------------------------------
; =============== S U B	R O U T	I N E =======================================


GuardStep_:				; CODE XREF: GuardStep:loc_1056p
					; GuardStep:loc_10A2p ...
		ld	a, (vGuardTmpY0)
		ld	b, a
		ld	a, (vGuardTmpX0)
		ld	c, a
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		cp	2	; CHR_LAD
		jp	z, loc_E9A
		inc	b
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		or	a	; CHR_SPACE
		jp	z, loc_E8C
		cp	5	; CHR_WATER
		jp	z, loc_E8C
		cp	7	; CHR_GOLD0
		jp	z, loc_E8C
		cp	8	; CHR_GOLD1
		jp	z, loc_E8C
		cp	0Eh	; CHR_STONESPACE
		jp	nc, loc_E8C
		dec	b
		ld	a, (vGuard_0)
		or	a
		jp	z, loc_E9A
		inc	b
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		dec	b
		cp	6	; CHR_BRIDGE
		jp	nz, loc_E9A
		inc	b

loc_E8C:				; CODE XREF: GuardStep_+17j
					; GuardStep_+1Cj ...
		ld	a, b
		ld	(vGuardTmpY1), a
		ld	a, c
		ld	(vGuardTmpX1), a
		ld	a, 1
		ld	(vGuard_0), a
		ret
; ---------------------------------------------------------------------------

loc_E9A:				; CODE XREF: GuardStep_+Ej
					; GuardStep_+33j ...
		xor	a
		ld	(vGuard_0), a
		ld	a, (PlayerPosY)
		ld	d, a
		ld	a, (PlayerPosX)
		ld	e, a
		cp	c
		jp	nc, loc_EEB
		dec	c
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		or	a	; CHR_SPACE
		jp	z, loc_ED5
		cp	2	; CHR_LAD
		jp	z, loc_ED5
		cp	5	; CHR_WATER
		jp	z, loc_ED5
		cp	6	; CHR_BRIDGE
		jp	z, loc_ED5
		cp	7	; CHR_GOLD0
		jp	z, loc_ED5
		cp	8	; CHR_GOLD1
		jp	z, loc_ED5
		cp	0Eh	; CHR_STONESPACE
		jp	nc, loc_ED5
		inc	c
		jp	loc_EEB
; ---------------------------------------------------------------------------

loc_ED5:				; CODE XREF: GuardStep_+66j
					; GuardStep_+6Bj ...
		ld	a, (vGuard_0+1)
		inc	a
		and	3
		ld	(vGuard_0+1), a
		jp	nz, loc_EE2
		inc	c

loc_EE2:				; CODE XREF: GuardStep_+94j
					; GuardStep_+DAj ...
		ld	a, b
		ld	(vGuardTmpY1), a
		ld	a, c
		ld	(vGuardTmpX1), a
		ret
; ---------------------------------------------------------------------------

loc_EEB:				; CODE XREF: GuardStep_+5Dj
					; GuardStep_+88j
		ld	a, c
		cp	e
		jp	nc, loc_F2B
		inc	c
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		or	a	; CHR_SPACE
		jp	z, loc_F1B
		cp	2	; CHR_LAD
		jp	z, loc_F1B
		cp	6	; CHR_BRIDGE
		jp	z, loc_F1B
		cp	5	; CHR_WATER
		jp	z, loc_F1B
		cp	7	; CHR_GOLD0
		jp	z, loc_F1B
		cp	8	; CHR_GOLD1
		jp	z, loc_F1B
		cp	0Eh	; CHRSTONE_SPACE
		jp	nc, loc_F1B
		dec	c
		jp	loc_F2B
; ---------------------------------------------------------------------------

loc_F1B:				; CODE XREF: GuardStep_+ACj
					; GuardStep_+B1j ...
		ld	a, (vGuard_0+1)
		inc	a
		and	3
		ld	(vGuard_0+1), a
		jp	nz, loc_EE2
		dec	c
		jp	loc_EE2
; ---------------------------------------------------------------------------

loc_F2B:				; CODE XREF: GuardStep_+A3j
					; GuardStep_+CEj
		ld	a, d
		cp	b
		jp	nc, loc_F6F
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		cp	2	; CHR_LAD
		jp	nz, loc_F6F
		dec	b
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		or	a	; CHR_SPACE
		jp	z, loc_F5F
		cp	2	; CHR_LAD
		jp	z, loc_F5F
		cp	5	; CHR_WATER
		jp	z, loc_F5F
		cp	7	; CHR_GOLD0
		jp	z, loc_F5F
		cp	8	; CHR_GOLD1
		jp	z, loc_F5F
		cp	0Eh	; CHR_STONESPACE
		jp	nc, loc_F5F
		inc	b
		jp	loc_F6F
; ---------------------------------------------------------------------------

loc_F5F:				; CODE XREF: GuardStep_+F5j
					; GuardStep_+FAj ...
		ld	a, (vGuard_0+1)
		inc	a
		and	3
		ld	(vGuard_0+1), a
		jp	nz, loc_EE2
		inc	b
		jp	loc_EE2
; ---------------------------------------------------------------------------

loc_F6F:				; CODE XREF: GuardStep_+E3j
					; GuardStep_+ECj ...
		ld	a, b
		cp	d
		jp	nc, loc_FA7
		inc	b
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		or	a	; CHR_SPACE
		jp	z, loc_F9A
		cp	2	; CHR_LAD
		jp	z, loc_F9A
		cp	5	; CHR_WATER
		jp	z, loc_F9A
		cp	7	; CHR_GOLD0
		jp	z, loc_F9A
		cp	8	; CHR_GOLD1
		jp	z, loc_F9A
		cp	0Eh	; CHR_STONESPACE
		jp	nc, loc_F9A
		dec	b
		jp	loc_FA7
; ---------------------------------------------------------------------------

loc_F9A:				; CODE XREF: GuardStep_+130j
					; GuardStep_+135j ...
		ld	a, (vGuard_0+1)
		inc	a
		and	3
		ld	(vGuard_0+1), a
		jp	nz, loc_EE2
		dec	b

loc_FA7:				; CODE XREF: GuardStep_+127j
					; GuardStep_+14Dj
		jp	loc_EE2
; End of function GuardStep_

; ---------------------------------------------------------------------------
vGuardTmpY0:	.DB	5

vGuardTmpX0:	.DB	8

vGuard_0:	.DW	200h

vGuardTmpY1:	.DB	5

vGuardTmpX1:	.DB	8

vGuard1YX:	.DW	805h
vGuard1_0:	.DW	200h

vGuard2YX:	.DW	0

vGuard2_0:	.DW	100h

vGuard3YX:	.DW	0

vGuard3_0:	.DW	200h

vGuard4YX:	.DW	0

vGuard4_0:	.DW	0


; =============== S U B	R O U T	I N E =======================================


sub_FC0:				; CODE XREF: GuardStep+20p
					; GuardStep+6Cp ...
		ld	a, (vGuardTmpY1)
		ld	b, a
		ld	a, (vGuardTmpX1)
		ld	c, a
		ld	hl, vGuard1YX
		ld	a, (hl)
		sub	b
		ld	d, a
		inc	hl
		ld	a, (hl)
		sub	c
		inc	hl
		or	d
		jp	z, loc_FFD
		inc	hl
		inc	hl
		ld	a, (hl)
		sub	b
		ld	d, a
		inc	hl
		ld	a, (hl)
		sub	c
		inc	hl
		or	d
		jp	z, loc_FFD
		inc	hl
		inc	hl
		ld	a, (hl)
		sub	b
		ld	d, a
		inc	hl
		ld	a, (hl)
		sub	c
		inc	hl
		or	d
		jp	z, loc_FFD
		inc	hl
		inc	hl
		ld	a, (hl)
		sub	b
		ld	d, a
		inc	hl
		ld	a, (hl)
		sub	c
		or	d
		jp	z, loc_FFD
		ret
; ---------------------------------------------------------------------------

loc_FFD:				; CODE XREF: sub_FC0+13j sub_FC0+20j ...
		ld	hl, (vGuardTmpY0)
		ld	(vGuardTmpY1), hl
		ret
; End of function sub_FC0


; =============== S U B	R O U T	I N E =======================================


PlaceGuard:				; CODE XREF: GuardStep+23p
					; GuardStep+6Fp ...
		ld	a, (vGuardTmpY0)
		ld	b, a
		ld	a, (vGuardTmpX0)
		ld	c, a
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		call	ToScreen_A_BC_XY_
		ld	a, (vGuardTmpY1)
		ld	b, a
		ld	a, (vGuardTmpX1)
		ld	c, a
		ld	a, 14h	; CHR_GUARD
		call	ToScreen_A_BC_XY_
		ret
; End of function PlaceGuard


; =============== S U B	R O U T	I N E =======================================


TestGuard:				; CODE XREF: GuardStep+26p
					; GuardStep+72p ...
		ld	a, (vGuardTmpY1)
		ld	b, a
		ld	a, (vGuardTmpX1)
		ld	c, a
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		cp	5	; CHR_WATER
		jp	nz, loc_1037
		call	ToScreen_A_BC_XY_
		xor	a
		ret
; ---------------------------------------------------------------------------

loc_1037:				; CODE XREF: TestGuard+Ej
		scf
		ret
; End of function TestGuard


; =============== S U B	R O U T	I N E =======================================


GuardStep:				; CODE XREF: GAME_RESTART+28p
		ld	hl, (vGuard1YX)
		ld	(vGuardTmpY0), hl
		ld	(vGuardTmpY1), hl
		ld	hl, (vGuard1_0)
		ld	(vGuard_0), hl
		ld	a, (vGuard1Cnt)
		or	a
		jp	z, loc_1056
		inc	a
		ld	(vGuard1Cnt), a
		jp	loc_107F
; ---------------------------------------------------------------------------

loc_1056:				; CODE XREF: GuardStep+13j
		call	GuardStep_
		call	sub_FC0
		call	PlaceGuard
		call	TestGuard
		jp	c, loc_1073
		ld	a, 208
		ld	(vGuard1Cnt), a
;		ld	hl, (LevelAttrib.Guard1StartPosY)
		ld	hl, (Guard1StartPosY)
		ld	(vGuard1YX), hl
		jp	loc_107F
; ---------------------------------------------------------------------------

loc_1073:				; CODE XREF: GuardStep+29j
		ld	hl, (vGuardTmpY1)
		ld	(vGuard1YX), hl
		ld	hl, (vGuard_0)
		ld	(vGuard1_0), hl

loc_107F:				; CODE XREF: GuardStep+1Aj
					; GuardStep+37j
;		ld	a, (LevelAttrib.GuardCount)
		ld	a, (GuardCount)
		cp	2
		ret	c
		ld	hl, (vGuard2YX)
		ld	(vGuardTmpY0), hl
		ld	(vGuardTmpY1), hl
		ld	hl, (vGuard2_0)
		ld	(vGuard_0), hl
		ld	a, (vGuard2Cnt)
		or	a
		jp	z, loc_10A2
		inc	a
		ld	(vGuard2Cnt), a
		jp	loc_10CB
; ---------------------------------------------------------------------------

loc_10A2:				; CODE XREF: GuardStep+5Fj
		call	GuardStep_
		call	sub_FC0
		call	PlaceGuard
		call	TestGuard
		jp	c, loc_10BF
		ld	a, 208
		ld	(vGuard2Cnt), a
;		ld	hl, (LevelAttrib.Guard2StartPosY)
		ld	hl, (Guard2StartPosY)
		ld	(vGuard2YX), hl
		jp	loc_10CB
; ---------------------------------------------------------------------------

loc_10BF:				; CODE XREF: GuardStep+75j
		ld	hl, (vGuardTmpY1)
		ld	(vGuard2YX), hl
		ld	hl, (vGuard_0)
		ld	(vGuard2_0), hl

loc_10CB:				; CODE XREF: GuardStep+66j
					; GuardStep+83j
;		ld	a, (LevelAttrib.GuardCount)
		ld	a, (GuardCount)
		cp	3
		ret	c
		ld	hl, (vGuard3YX)
		ld	(vGuardTmpY0), hl
		ld	(vGuardTmpY1), hl
		ld	hl, (vGuard3_0)
		ld	(vGuard_0), hl
		ld	a, (vGuard3Cnt)
		or	a
		jp	z, loc_10EE
		inc	a
		ld	(vGuard3Cnt), a
		jp	loc_1117
; ---------------------------------------------------------------------------

loc_10EE:				; CODE XREF: GuardStep+ABj
		call	GuardStep_
		call	sub_FC0
		call	PlaceGuard
		call	TestGuard
		jp	c, loc_110B
		ld	a, 208
		ld	(vGuard3Cnt), a
;		ld	hl, (LevelAttrib.Guard3StartPosY)
		ld	hl, (Guard3StartPosY)
		ld	(vGuard3YX), hl
		jp	loc_1117
; ---------------------------------------------------------------------------

loc_110B:				; CODE XREF: GuardStep+C1j
		ld	hl, (vGuardTmpY1)
		ld	(vGuard3YX), hl
		ld	hl, (vGuard_0)
		ld	(vGuard3_0), hl

loc_1117:				; CODE XREF: GuardStep+B2j
					; GuardStep+CFj
;		ld	a, (LevelAttrib.GuardCount)
		ld	a, (GuardCount)
		cp	4
		ret	c
		ld	hl, (vGuard4YX)
		ld	(vGuardTmpY0), hl
		ld	(vGuardTmpY1), hl
		ld	hl, (vGuard4_0)
		ld	(vGuard_0), hl
		ld	a, (vGuard4Cnt)
		or	a
		jp	z, loc_113A
		inc	a
		ld	(vGuard4Cnt), a
		jp	locret_1163
; ---------------------------------------------------------------------------

loc_113A:				; CODE XREF: GuardStep+F7j
		call	GuardStep_
		call	sub_FC0
		call	PlaceGuard
		call	TestGuard
		jp	c, loc_1157
		ld	a, 208
		ld	(vGuard4Cnt), a
;		ld	hl, (LevelAttrib.Guard4StartPosY)
		ld	hl, (Guard4StartPosY)
		ld	(vGuard4YX), hl
		jp	locret_1163
; ---------------------------------------------------------------------------

loc_1157:				; CODE XREF: GuardStep+10Dj
		ld	hl, (vGuardTmpY1)
		ld	(vGuard4YX), hl
		ld	hl, (vGuard_0)
		ld	(vGuard4_0), hl

locret_1163:				; CODE XREF: GuardStep+FEj
					; GuardStep+11Bj
		ret
; End of function GuardStep

; ---------------------------------------------------------------------------
vGuard1Cnt:	.DB	0			; DATA XREF: GuardStep+Fr
					; GuardStep+17w ...
vGuard2Cnt:	.DB	0			; DATA XREF: GuardStep+5Br
					; GuardStep+63w ...
vGuard3Cnt:	.DB	0			; DATA XREF: GuardStep+A7r
					; GuardStep+AFw ...
vGuard4Cnt:	.DB	0			; DATA XREF: GuardStep+F3r
					; GuardStep+FBw ...

; =============== S U B	R O U T	I N E =======================================


COPY_GuardAttrib:			; CODE XREF: GAME_RESTART+1Cp
;		ld	hl, (LevelAttrib.Guard1StartPosY)
		ld	hl, (Guard1StartPosY)
		ld	(vGuard1YX), hl
;		ld	hl, (LevelAttrib.Guard2StartPosY)
		ld	hl, (Guard2StartPosY)
		ld	(vGuard2YX), hl
;		ld	hl, (LevelAttrib.Guard3StartPosY)
		ld	hl, (Guard3StartPosY)
		ld	(vGuard3YX), hl
;		ld	hl, (LevelAttrib.Guard4StartPosY)
		ld	hl, (Guard4StartPosY)
		ld	(vGuard4YX), hl
		ret
; End of function COPY_GuardAttrib


; =============== S U B	R O U T	I N E =======================================


PlayerVsGuard:				; CODE XREF: GAME_RESTART+2Bp
		ld	hl, (PlayerPosY)
		ex	de, hl
		ld	hl, (vGuard1YX)
		ld	a, d
		sub	h
		jp	nz, loc_1192
		ld	a, e
		sub	l
		jp	z, loc_11BE

loc_1192:				; CODE XREF: PlayerVsGuard+9j
		ld	hl, (vGuard2YX)
		ld	a, d
		sub	h
		jp	nz, loc_119F
		ld	a, e
		sub	l
		jp	z, loc_11BE

loc_119F:				; CODE XREF: PlayerVsGuard+16j
		ld	hl, (vGuard3YX)
		ld	a, d
		sub	h
		jp	nz, loc_11AC
		ld	a, e
		sub	l
		jp	z, loc_11BE

loc_11AC:				; CODE XREF: PlayerVsGuard+23j
		ld	hl, (vGuard4YX)
		ld	a, d
		sub	h
		jp	nz, loc_11B9
		ld	a, e
		sub	l
		jp	z, loc_11BE

loc_11B9:				; CODE XREF: PlayerVsGuard+30j
		xor	a

loc_11BA:				; CODE XREF: PlayerVsGuard+3Fj
		ld	(vLevelChange),	a
		ret
; ---------------------------------------------------------------------------

loc_11BE:				; CODE XREF: PlayerVsGuard+Ej
					; PlayerVsGuard+1Bj ...
		ld	a, 1
		jp	loc_11BA
; End of function PlayerVsGuard

; ---------------------------------------------------------------------------
vLevelChange:	.DB	0			; DATA XREF: GAME_RESTART+3Ar
					; PlayerVsGuard:loc_11BAw ...

; =============== S U B	R O U T	I N E =======================================


ToScreen_A_BC_XY_:			; CODE XREF: OUT_Map???+78p
					; PlayerStep+33p ...
		push	af
		push	de
		push	hl
		call	CONVERT_CHAR

	LD	H, B
	LD	L, C
;	LD	(SCR_POS), HL
	ld	a, (CONVERTED_CHAR)
	CALL	0FF90h

		pop	hl
		pop	de
		pop	af
		ret
; End of function ToScreen_A_BC_XY_


; =============== S U B	R O U T	I N E =======================================


GETShutBuf:				; CODE XREF: sub_13A4:loc_13A8p
					; sub_1460:loc_1467p ...
		push	af
		push	de
		ld	de, ShutBuffer
		xor	a
		ld	h, A
		ld	a, (ShutBufPtr)
		ld	L, A
		add	hl, hl
		add	hl, hl
		add	hl, de
		pop	de
		pop	af
		ret
; End of function GETShutBuf

; ---------------------------------------------------------------------------
; =============== S U B	R O U T	I N E =======================================


sub_13A4:				; CODE XREF: PlayerShut+35p
		xor	a
		ld	(ShutBufPtr), a

loc_13A8:				; CODE XREF: sub_13A4+15j
		call	GETShutBuf
		ld	a, (hl)
		or	a
		jp	nz, loc_13C9

loc_13B0:				; CODE XREF: sub_13A4+4Dj sub_13A4+62j ...
		ld	a, (ShutBufPtr)
		inc	a
		ld	(ShutBufPtr), a
		cp	100
		jp	c, loc_13A8
		ld	a, (PlayerPosY)
		ld	b, a
		ld	a, (PlayerPosX)
		ld	c, a
		ld	a, 13h
		jp	ToScreen_A_BC_XY_
; ---------------------------------------------------------------------------

loc_13C9:				; CODE XREF: sub_13A4+9j
		inc	hl
		ld	a, (hl)
		dec	a
		ld	b, a
		ld	a, (vShutCounter)
		and	7
		ld	a, b
		jp	z, loc_13D7
		inc	a

loc_13D7:				; CODE XREF: sub_13A4+2Fj
		ld	(hl), a
		or	a
		jp	m, loc_1431
		jp	nz, loc_13F4

loc_13DF:				; CODE XREF: sub_13A4+8Fj
		xor	a
		ld	(hl), a
		dec	hl
		ld	(hl), a
		inc	hl
		inc	hl
		ld	b, (hl)
		inc	hl
		ld	c, (hl)
		call	MapDstADDR_BCtoHL
		ld	a, 0Bh	; CHR_BRICK
		ld	(hl), a
		call	ToScreen_A_BC_XY_
		jp	loc_13B0
; ---------------------------------------------------------------------------

loc_13F4:				; CODE XREF: sub_13A4+38j
		cp	1Eh
		jp	nc, loc_1409
		inc	hl
		ld	b, (hl)
		inc	hl
		ld	c, (hl)
		call	MapDstADDR_BCtoHL
		ld	a, 0Ch	; CHR_BRICK1
		ld	(hl), a
		call	ToScreen_A_BC_XY_
		jp	loc_13B0
; ---------------------------------------------------------------------------

loc_1409:				; CODE XREF: sub_13A4+52j
		cp	3Ch ; '<'
		jp	nc, loc_141E
		inc	hl
		ld	b, (hl)
		inc	hl
		ld	c, (hl)
		call	MapDstADDR_BCtoHL
		ld	a, 0Dh	; CHR_BRICK2
		ld	(hl), a
		call	ToScreen_A_BC_XY_
		jp	loc_13B0
; ---------------------------------------------------------------------------

loc_141E:				; CODE XREF: sub_13A4+67j sub_13A4+A9j
		or	80h ; '€'
		ld	(hl), a
		inc	hl
		ld	b, (hl)
		inc	hl
		ld	c, (hl)
		call	MapDstADDR_BCtoHL
		ld	a, 0Eh	; CHR_STONESPACE
		ld	(hl), a
		call	ToScreen_A_BC_XY_
		jp	loc_13B0
; ---------------------------------------------------------------------------

loc_1431:				; CODE XREF: sub_13A4+35j
		and	7Fh ; ''
		jp	z, loc_13DF
		cp	1Eh
		jp	nc, loc_144B
		inc	hl
		ld	b, (hl)
		inc	hl
		ld	c, (hl)
		call	MapDstADDR_BCtoHL
		ld	a, 10h	; CHR_BRICK4
		ld	(hl), a
		call	ToScreen_A_BC_XY_
		jp	loc_13B0
; ---------------------------------------------------------------------------

loc_144B:				; CODE XREF: sub_13A4+94j
		cp	3Ch ; '<'
		jp	nc, loc_141E
		inc	hl
		ld	b, (hl)
		inc	hl
		ld	c, (hl)
		call	MapDstADDR_BCtoHL
		ld	a, 0Fh	; CHR_BRICK3
		ld	(hl), a
		call	ToScreen_A_BC_XY_
		jp	loc_13B0
; End of function sub_13A4


; =============== S U B	R O U T	I N E =======================================


sub_1460:				; CODE XREF: ShutStep:loc_14F8p
		push	af
		push	de
		push	hl
		xor	a
		ld	(ShutBufPtr), a

loc_1467:				; CODE XREF: sub_1460+18j
		call	GETShutBuf
		ld	a, (hl)
		or	a
		jp	nz, loc_1497

loc_146F:				; CODE XREF: sub_1460+3Bj sub_1460+41j
		ld	a, (ShutBufPtr)
		inc	a
		ld	(ShutBufPtr), a
		cp	100
		jp	c, loc_1467
		xor	a
		ld	(ShutBufPtr), a

loc_147F:				; CODE XREF: sub_1460+30j
		call	GETShutBuf
		ld	a, (hl)
		or	a
		jp	z, loc_14A7
		ld	a, (ShutBufPtr)
		inc	a
		ld	(ShutBufPtr), a
		cp	100
		jp	c, loc_147F

loc_1493:				; CODE XREF: sub_1460+44j sub_1460+4Ej
		pop	hl
		pop	de
		pop	af
		ret
; ---------------------------------------------------------------------------

loc_1497:				; CODE XREF: sub_1460+Cj
		inc	hl
		inc	hl
		ld	a, (hl)
		cp	b
		jp	nz, loc_146F
		inc	hl
		ld	a, (hl)
		cp	c
		jp	nz, loc_146F
		jp	loc_1493
; ---------------------------------------------------------------------------

loc_14A7:				; CODE XREF: sub_1460+24j
		inc	a
		ld	(hl), a
		inc	hl
		inc	hl
		ld	(hl), b
		inc	hl
		ld	(hl), c
		jp	loc_1493
; End of function sub_1460


; =============== S U B	R O U T	I N E =======================================


ShutStep:				; CODE XREF: PlayerShut:loc_1578p
		ld	a, (ShutLeftCnt)
		or	a
		jp	nz, loc_14C0
		ld	a, (ShutRightCnt)
		or	a
		jp	nz, loc_150B
		ret
; ---------------------------------------------------------------------------

loc_14C0:				; CODE XREF: ShutStep+4j
		ld	hl, (ShutLeftPos)
		ld	c, h
		ld	b, l
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		call	ToScreen_A_BC_XY_
		dec	c
		ld	h, c
		ld	l, b
		ld	(ShutLeftPos), hl
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		cp	1	; CHR_STONE
		jp	nz, loc_14E0
		xor	a
		ld	(ShutLeftCnt), a
		ret
; ---------------------------------------------------------------------------

loc_14E0:				; CODE XREF: ShutStep+27j
		cp	0Bh	; CHR_BRICK
		jp	z, loc_14F4
		cp	0Ch	; CHR_BRICK1
		jp	z, loc_14F4
		cp	0Dh	; CHR_BRICK2
		jp	z, loc_14F4
		ld	a, 15h	; CHR_-
		jp	ToScreen_A_BC_XY_
; ---------------------------------------------------------------------------

loc_14F4:				; CODE XREF: ShutStep+31j ShutStep+36j ...
		xor	a
		ld	(ShutLeftCnt), a

loc_14F8:				; CODE XREF: ShutStep+92j
		call	sub_1460
		call	GETShutBuf
		inc	hl
		ld	a, (hl)
		add	a, 30
		cp	59
		jp	c, loc_1509
		ld	a, 127

loc_1509:				; CODE XREF: ShutStep+53j
		ld	(hl), a
		ret
; ---------------------------------------------------------------------------

loc_150B:				; CODE XREF: ShutStep+Bj
		ld	hl, (ShutRightPos)
		ld	c, h
		ld	b, l
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		call	ToScreen_A_BC_XY_
		inc	c
		ld	l, b
		ld	h, c
		ld	(ShutRightPos),	hl
		call	MapDstADDR_BCtoHL
		ld	a, (hl)
		cp	1	; CHR_STONE
		jp	nz, loc_152B
		xor	a
		ld	(ShutRightCnt),	a
		ret
; ---------------------------------------------------------------------------

loc_152B:				; CODE XREF: ShutStep+72j
		cp	0Bh	; CHR_BRICK
		jp	z, loc_153F
		cp	0Ch	; CHR_BRICK1
		jp	z, loc_153F
		cp	0Dh	; CHR_BRICK2
		jp	z, loc_153F
		ld	a, 15h	; CHR_-
		jp	ToScreen_A_BC_XY_
; ---------------------------------------------------------------------------

loc_153F:				; CODE XREF: ShutStep+7Cj ShutStep+81j ...
		xor	a
		ld	(ShutRightCnt),	a
		jp	loc_14F8
; End of function ShutStep


; =============== S U B	R O U T	I N E =======================================


PlayerShut:				; CODE XREF: GAME_RESTART+31p
					; GAME_RESTART+34p
		ld	a, (KeyPressed)
		cp	'e'
		jp	nz, loc_155F
		ld	a, (ShutRightCnt)
		or	a
		jp	nz, loc_155F
		inc	a
		ld	(ShutRightCnt),	a
		ld	hl, (PlayerPosY)
		ld	(ShutRightPos),	hl

loc_155F:				; CODE XREF: PlayerShut+5j
					; PlayerShut+Cj
		ld	a, (KeyPressed)
		cp	'q'
		jp	nz, loc_1578
		ld	a, (ShutLeftCnt)
		or	a
		jp	nz, loc_1578
		inc	a
		ld	(ShutLeftCnt), a
		ld	hl, (PlayerPosY)
		ld	(ShutLeftPos), hl

loc_1578:				; CODE XREF: PlayerShut+1Ej
					; PlayerShut+25j
		call	ShutStep
		call	sub_13A4
		ld	a, (vShutCounter)
		inc	a
		ld	(vShutCounter),	a
		ret
; End of function PlayerShut


; =============== S U B	R O U T	I N E =======================================


Clear_ShutBuf:				; CODE XREF: GAME_RESTART+19p
		xor	a
		ld	(ShutRightCnt),	a
		ld	(ShutLeftCnt), a
		ld	hl, ShutBuffer
		ld	b, 200

loc_1592:				; CODE XREF: Clear_ShutBuf+11j
		ld	(hl), a
		inc	hl
		ld	(hl), a
		inc	hl
		dec	b
		jp	nz, loc_1592
		ret
; End of function Clear_ShutBuf

; ---------------------------------------------------------------------------
ShutRightCnt:	.DB	0			; DATA XREF: ShutStep+7r ShutStep+76w	...
ShutLeftCnt:	.DB	0			; DATA XREF: ShutStepr	ShutStep+2Bw ...
ShutLeftPos:	.DW	1D11h		; DATA XREF: ShutStep:loc_14C0r
					; ShutStep+1Ew	...
ShutRightPos:	.DW	140Bh		; DATA XREF: ShutStep:loc_150Br
					; ShutStep+69w	...

; =============== S U B	R O U T	I N E =======================================


GameSpeed:				; CODE XREF: GAME_RESTART+2Ep
		ld	a, (KeyPressed)
		cp	30h ; '0'
		jp	c, loc_15B7
		cp	3Ah ; ':'
		jp	nc, loc_15B7
		and	0Fh
		rlca
		rlca
		rlca
		inc	a
		ld	(vGameSpeed), a

loc_15B7:				; CODE XREF: GameSpeed+5j GameSpeed+Aj
		ld	a, (vGameSpeed)
		ld	b, a

loc_15BB:				; CODE XREF: GameSpeed+21j
		ld	a, 0FFh

loc_15BD:				; CODE XREF: GameSpeed+1Dj
		dec	a
		jp	nz, loc_15BD
		dec	b
		jp	nz, loc_15BB
		ret
; End of function GameSpeed

; ---------------------------------------------------------------------------
vGameSpeed:	.DB	29h			; DATA XREF: GameSpeed+13w
					; GameSpeed:loc_15B7r

; =============== S U B	R O U T	I N E =======================================


CHECK_LevelEnd:				; CODE XREF: GAME_RESTART+37p
		ld	a, (KeyPressed)
		cp	2Eh ; '.'
		jp	z, loc_15E6
		cp	3Ah ; ':'
		jp	z, 0h
		ld	hl, (PlayerPosY)
;		ld	a, (LevelAttrib.ExitPosY)
		ld	a, (ExitPosY)
		cp	l
		jp	nz, locret_15E5
;		ld	a, (LevelAttrib.ExitPosX)
		ld	a, (ExitPosX)
		cp	h
		jp	z, loc_15E6

locret_15E5:				; CODE XREF: CHECK_LevelEnd+14j
		ret
; ---------------------------------------------------------------------------

loc_15E6:				; CODE XREF: CHECK_LevelEnd+5j
					; CHECK_LevelEnd+1Bj
		ld	a, (vLevel)
		inc	a
		ld	(vLevel), a
		ld	hl, Levels
		ld	de, 0
		rla
		ld	e, a
		add	hl, de
		ld	a, (hl)
		inc	hl
		or	(hl)
		jp	nz, loc_15FF
		ld	(vLevel), a

loc_15FF:				; CODE XREF: CHECK_LevelEnd+32j
		ld	a, 1
		ld	(vLevelChange),	a
		ret
; End of function CHECK_LevelEnd

; =============== S U B	R O U T	I N E =======================================


KEY_INC:				; CODE XREF: PlayerStep+C5p
					; PlayerStep+129p ...
		ld	a, (vKEYCnt)
		inc	a
		ld	(vKEYCnt), a
		ld	(hl), 12h	; CHR_APPLE
;		push	bc
;		ld	c, 7
;		call	0F809h
;		pop	bc
		ret
; End of function KEY_INC

; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
byte_1612:	.DB	1Fh,	1Bh, 59h, 22h, 36h, 17h, 20h, 20h, 17h,	20h, 20h
					; DATA XREF: ROM:1609o
		.DB	20h,	17h, 17h, 17h, 20h, 20h, 20h, 17h, 17h,	17h, 20h
		.DB	20h,	20h, 17h, 17h, 17h, 1Bh, 59h, 23h, 36h,	17h, 20h
		.DB	17h,	20h, 20h, 20h, 17h, 20h, 20h, 17h, 20h,	20h, 17h
		.DB	20h,	20h, 17h, 20h, 20h, 17h, 20h, 20h, 17h,	1Bh, 59h
		.DB	24h,	36h, 17h, 17h, 20h, 20h, 20h, 20h, 17h,	20h, 20h
		.DB	17h,	20h, 20h, 17h, 20h, 20h, 17h, 20h, 20h,	17h, 20h
		.DB	20h,	17h, 1Bh, 59h, 25h, 36h, 17h, 20h, 17h,	20h, 20h
		.DB	20h,	17h, 20h, 20h, 17h, 20h, 20h, 17h, 17h,	17h, 17h
		.DB	20h,	20h, 17h, 20h, 20h, 17h, 1Bh, 59h, 26h,	36h, 17h
		.DB	20h,	20h, 17h, 20h, 20h, 17h, 20h, 20h, 17h,	20h, 20h
		.DB	17h,	20h, 20h, 17h, 20h, 17h, 17h, 17h, 17h,	17h, 17h
		.DB	1Bh,	59h, 28h, 3Ch, 72h, 69h, 67h, 61h, 20h,	2Ah, 20h
		.DB	31h,	39h, 38h, 37h, 1Bh, 59h, 29h, 3Ch, 77h,	65h, 72h
		.DB	73h,	69h, 71h, 20h, 20h, 31h, 2Eh, 34h, 1Bh,	59h, 2Ah
		.DB	36h,	61h, 77h, 74h, 6Fh, 72h, 20h, 70h, 75h,	6Ah, 73h
		.DB	69h,	73h, 2Dh, 70h, 75h, 6Ah, 7Bh, 65h, 20h,	7Ch, 2Eh
		.DB	69h,	2Eh, 1Bh, 59h, 2Ch, 2Dh, 77h, 61h, 7Bh,	61h, 20h
		.DB	7Ah,	61h, 64h, 61h, 7Eh, 61h, 20h, 73h, 6Fh,	73h, 74h
		.DB	6Fh,	69h, 74h, 20h, 77h, 20h, 74h, 6Fh, 6Dh,	20h, 7Eh
		.DB	74h,	6Fh, 62h, 79h, 20h, 70h, 72h, 6Fh, 6Ah,	74h, 69h
		.DB	1Bh,	59h, 2Dh, 2Ch, 6Ch, 61h, 62h, 69h, 72h,	69h, 6Eh
		.DB	74h,	79h, 2Ch, 6Eh, 61h, 68h, 6Fh, 64h, 71h,	20h, 70h
		.DB	6Fh,	20h, 64h, 6Fh, 72h, 6Fh, 67h, 65h, 20h,	6Bh, 6Ch
		.DB	61h,	64h, 2Dh, 1Eh, 2Ch, 73h, 70h, 72h, 71h,	74h, 61h
		.DB	6Eh,	2Dh, 1Bh, 59h, 2Eh, 2Ch, 6Eh, 79h, 6Ah,	20h, 77h
		.DB	20h,	73h, 75h, 6Eh, 64h, 75h, 6Bh, 65h, 2Dh,	14h, 2Eh
		.DB	1Bh,	59h, 2Fh, 2Dh, 6Eh, 65h, 6Fh, 62h, 68h,	6Fh, 64h
		.DB	69h,	6Dh, 6Fh, 20h, 74h, 61h, 6Bh, 76h, 65h,	20h, 6Fh
		.DB	73h,	74h, 65h, 72h, 65h, 67h, 61h, 74h, 78h,	73h, 71h
		.DB	20h,	6Ch, 60h, 64h, 6Fh, 65h, 64h, 6Fh, 77h,	2Dh, 0Bh
		.DB	2Ch,	1Bh, 59h, 30h, 2Ch, 69h, 20h, 6Eh, 65h,	20h, 75h
		.DB	74h,	6Fh, 6Eh, 75h, 74h, 78h, 20h, 77h, 20h,	77h, 6Fh
		.DB	64h,	65h, 2Dh, 5Eh, 5Eh, 5Eh, 2Eh, 1Bh, 59h,	31h, 2Dh
		.DB	73h,	74h, 65h, 6Eh, 79h, 2Ch, 73h, 64h, 65h,	6Ch, 61h
		.DB	6Eh,	6Eh, 79h, 65h, 20h, 69h, 7Ah, 20h, 64h,	65h, 72h
		.DB	65h,	77h, 61h, 2Dh, 25h, 2Ch, 6Dh, 6Fh, 76h,	6Eh, 6Fh
		.DB	20h,	6Ch, 6Fh, 6Dh, 61h, 74h, 78h, 1Bh, 59h,	32h, 2Ch
		.DB	70h,	72h, 69h, 20h, 70h, 6Fh, 6Dh, 6Fh, 7Dh,	69h, 20h
		.DB	6Bh,	6Ch, 61h, 77h, 69h, 7Bh, 20h, 22h, 51h,	22h, 20h
		.DB	69h,	20h, 22h, 5Eh, 22h, 1Bh, 59h, 33h, 2Dh,	77h, 79h
		.DB	20h,	69h, 7Ah, 6Fh, 62h, 72h, 61h, 76h, 61h,	65h, 74h
		.DB	65h,	73h, 78h, 2Dh, 9, 2Ch, 20h, 62h, 65h, 74h, 6Fh
		.DB	6Eh,	6Eh, 79h, 65h, 20h, 73h, 74h, 65h, 6Eh,	79h, 2Dh
		.DB	58h,	1Bh, 59h, 34h, 2Ch, 64h, 77h, 65h, 72h,	69h, 2Dh
		.DB	5Dh,	20h, 69h, 20h, 5Bh, 2Ch, 20h, 6Dh, 6Fh,	73h, 74h
		.DB	69h,	6Bh, 69h, 2Dh, 20h, 1Ch, 2Ch, 20h, 6Ch,	65h, 73h
		.DB	74h,	6Eh, 69h, 63h, 79h, 2Dh, 23h, 2Eh, 1Bh,	59h, 35h
		.DB	2Dh,	75h, 70h, 72h, 61h, 77h, 6Ch, 71h, 74h,	78h, 20h
		.DB	73h,	77h, 6Fh, 69h, 6Dh, 20h, 64h, 77h, 69h,	76h, 65h
		.DB	6Eh,	69h, 65h, 6Dh, 20h, 77h, 79h, 20h, 6Dh,	6Fh, 76h
		.DB	65h,	74h, 65h, 20h, 70h, 72h, 69h, 1Bh, 59h,	36h, 2Ch
		.DB	70h,	6Fh, 6Dh, 6Fh, 7Dh, 69h, 20h, 6Bh, 6Ch,	61h, 77h
		.DB	69h,	7Bh, 20h, 75h, 70h, 72h, 61h, 77h, 6Ch,	65h, 6Eh
		.DB	69h,	71h, 20h, 6Bh, 75h, 72h, 73h, 6Fh, 72h,	6Fh, 6Dh
		.DB	2Ch,	69h, 7Ah, 6Dh, 65h, 6Eh, 71h, 74h, 78h,	1Bh, 59h
		.DB	37h,	2Ch, 73h, 6Bh, 6Fh, 72h, 6Fh, 73h, 74h,	78h, 20h
		.DB	6Bh,	6Ch, 61h, 77h, 69h, 7Bh, 61h, 6Dh, 69h,	20h, 22h
		.DB	30h,	2Dh, 39h, 22h, 2Eh, 0


; ---------------------------------------------------------------------------

Level0:		.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:Levelso
		.DB	   1, 16h, 17h,   0,	3Fh
		.DB	   1,   1, 17h, 3Ch,	3Fh
		.DB	   5, 16h, 16h, 12h,	3Bh
		.DB	   2, 12h, 15h, 0Eh,	0Fh
		.DB	 0Bh, 12h, 12h, 0Ah,	0Dh
		.DB	   7, 11h, 11h, 0Ah,	0Ah
		.DB	 0Bh, 12h, 12h, 10h,	19h
		.DB	   2, 0Eh, 11h, 14h,	15h
		.DB	 0Bh, 0Eh, 0Eh, 16h,	1Dh
		.DB	   2, 0Ah, 0Dh, 1Ch,	1Dh
		.DB	 0Bh, 0Ah, 0Ah, 1Eh,	29h
		.DB	   2, 0Ah, 11h, 26h,	27h
		.DB	 0Bh, 12h, 12h, 1Eh,	29h
		.DB	   7, 11h, 11h, 1Eh,	1Eh
		.DB	 0Bh, 0Eh, 0Eh, 28h,	2Fh
		.DB	   2, 0Eh, 11h, 30h,	31h
		.DB	   7,   9,	9, 1Eh,	1Eh
		.DB	 0Bh, 12h, 12h, 30h,	37h
		.DB	   2, 0Ah, 11h, 36h,	37h
		.DB	 0Bh, 0Ah, 0Ah, 30h,	35h
		.DB	   7,   9,	9, 30h,	30h
		.DB	   2,   6,	9, 32h,	33h
		.DB	 0Bh,   6,	6, 12h,	31h
		.DB	   6,   6,	6, 1Eh,	27h
		.DB	   2,   6,	9, 14h,	15h
		.DB	 0Bh, 0Ah, 0Ah, 0Ah,	15h
		.DB	   7,   9,	9, 0Ah,	0Ah
		.DB	   2, 0Ah, 0Dh, 0Ch,	0Dh
		.DB	 0Bh, 0Eh, 0Eh,   4,	0Dh
		.DB	 0Bh,   6,	6,   4,	0Bh
		.DB	   2,   6, 0Dh,   6,	  7
		.DB	 0Bh,   3,	3, 0Ch,	35h
		.DB	   6,   3,	3, 14h,	19h
		.DB	   7,   2,	2, 20h,	20h
		.DB	   6,   3,	3, 26h,	2Bh
		.DB	 0Bh,   1,	1,   4,	2Dh
		.DB	 0Bh,   1,	1, 30h,	3Bh
		.DB	   2,   1,	2, 35h,	35h
		.DB	   2,   3,	5, 0Ah,	0Bh
		.DB	   0
;Level0Attrib:	tLevelAttr < 0Fh,    4,	   1,  2Eh, 0, 0, 0, 0,	0, 0, 0,    1,	35h>
Level0Attrib:	.DB	0Fh,    4,	   1,  2Eh, 0, 0, 0, 0,	0, 0, 0,    1,	35h

Level1:		.DB	   1,   1, 16h,   0,	  1 ; DATA XREF: ROM:01D2o
		.DB	   1, 16h, 16h,   0,	3Fh
		.DB	   1,   1, 14h,   3,	  3
		.DB	   1,   1, 16h, 1Eh,	1Fh
		.DB	   5, 16h, 16h, 0Ah,	17h
		.DB	 0Bh,   1,	1,   4,	1Dh
		.DB	   2, 12h, 15h,   9,	  9
		.DB	 0Bh, 14h, 14h, 0Ah,	13h
		.DB	   1, 17h, 17h,   0,	3Fh
		.DB	   6, 14h, 14h, 0Eh,	0Eh
		.DB	   6, 14h, 14h, 12h,	12h
		.DB	   6, 12h, 12h,   8,	  8
		.DB	 0Bh, 12h, 12h, 0Ah,	14h
		.DB	   6, 12h, 12h, 0Eh,	0Eh
		.DB	   6, 12h, 12h, 12h,	12h
		.DB	 0Bh, 10h, 10h,   8,	0Dh
		.DB	   6, 10h, 10h, 0Eh,	0Eh
		.DB	   2, 0Eh, 0Fh,   9,	  9
		.DB	 0Bh, 0Eh, 0Eh,   4,	  8
		.DB	   6, 0Eh, 0Eh,   5,	  6
		.DB	   2,   3, 0Dh,   4,	  4
		.DB	   7, 10h, 10h,   4,	  4
		.DB	   7, 12h, 12h,   4,	  4
		.DB	 0Bh, 11h, 11h,   4,	  5
		.DB	 0Bh, 13h, 13h,   4,	  6
		.DB	 0Bh, 0Ch, 0Ch,   7,	11h
		.DB	   6, 0Ch, 0Ch, 0Ch,	0Ch
		.DB	   7, 0Bh, 0Bh, 11h,	11h
		.DB	 0Bh, 0Ch, 0Ch, 13h,	16h
		.DB	   7, 0Bh, 0Bh, 13h,	13h
		.DB	   2, 0Ch, 11h, 0Fh,	0Fh
		.DB	 0Bh,   9,	9,   6,	0Eh
		.DB	   6,   9,	9, 0Ch,	0Ch
		.DB	 0Bh, 0Ah, 0Ah, 0Eh,	15h
		.DB	   7,   9,	9, 11h,	11h
		.DB	   2,   3, 0Bh,   9,	  9
		.DB	 0Bh,   3,	5,   5,	  6
		.DB	 0Bh,   5,	5,   8,	  8
		.DB	   6,   5,	5,   7,	  7
		.DB	 0Bh,   4,	4, 0Ah,	1Dh
		.DB	 0Bh,   3,	3, 0Ah,	0Bh
		.DB	   6,   4,	4, 0Ch,	0Ch
		.DB	 0Bh,   3,	3, 14h,	18h
		.DB	   2,   3,	3, 13h,	13h
		.DB	   6,   4,	4, 19h,	19h
		.DB	   2,   4,	6, 0Eh,	0Eh
		.DB	   8,   6,	6, 0Dh,	0Dh
		.DB	 0Bh,   7,	7, 0Dh,	15h
		.DB	 0Bh,   8,	8, 15h,	17h
		.DB	   2,   6,	7, 16h,	16h
		.DB	   2,   8, 0Eh, 18h,	18h
		.DB	 0Bh, 0Fh, 0Fh, 10h,	18h
		.DB	 0Bh, 0Eh, 0Eh, 13h,	15h
		.DB	   6, 0Fh, 0Fh, 12h,	12h
		.DB	   6, 0Fh, 0Fh, 16h,	16h
		.DB	   2,   1, 0Dh, 1Ch,	1Ch
		.DB	 0Ah,   5,	5, 18h,	18h
		.DB	 0Bh,   6,	6, 17h,	1Ch
		.DB	   6,   9,	9, 19h,	1Bh
		.DB	 0Bh, 0Eh, 0Eh, 1Ch,	1Ch
		.DB	   2, 0Eh, 12h, 1Bh,	1Bh
		.DB	 0Bh, 11h, 11h, 17h,	19h
		.DB	 0Bh, 13h, 13h, 16h,	1Bh
		.DB	   2, 11h, 15h, 18h,	18h
		.DB	 0Bh, 11h, 15h, 1Dh,	1Dh
		.DB	   7, 10h, 10h, 1Dh,	1Dh
		.DB	 0Bh, 11h, 11h, 1Ch,	1Ch
		.DB	   7, 14h, 14h, 1Ch,	1Ch
		.DB	 0Bh, 15h, 15h, 1Bh,	1Ch
		.DB	 0Bh, 16h, 16h, 22h,	3Dh
		.DB	   5, 16h, 16h, 38h,	3Ch
		.DB	   1,   1, 16h, 3Eh,	3Fh
		.DB	   1,   1,	1, 31h,	3Dh
		.DB	   1,   1,	1, 22h,	2Eh
		.DB	   1,   1, 14h, 21h,	21h
		.DB	   2,   3, 15h, 22h,	22h
		.DB	   1, 11h, 12h, 23h,	32h
		.DB	   5, 11h, 11h, 26h,	31h
		.DB	   1, 0Fh, 10h, 32h,	32h
		.DB	   6, 0Fh, 0Fh, 31h,	31h
		.DB	 0Bh, 0Fh, 0Fh, 2Ch,	30h
		.DB	 0Bh, 0Fh, 0Fh, 24h,	2Ah
		.DB	   6, 0Fh, 0Fh, 25h,	27h
		.DB	   2,   9, 0Eh, 24h,	24h
		.DB	 0Bh,   9,	9, 25h,	25h
		.DB	   6,   9,	9, 26h,	26h
		.DB	 0Bh,   3,	5, 23h,	25h
		.DB	   7,   4,	4, 24h,	24h
		.DB	   6,   4,	4, 26h,	27h
		.DB	   7,   6,	6, 25h,	25h
		.DB	 0Bh,   7,	7, 25h,	25h
		.DB	   1, 0Dh, 0Dh, 26h,	30h
		.DB	   6, 0Dh, 0Dh, 28h,	28h
		.DB	   6, 0Dh, 0Dh, 2Ch,	2Ch
		.DB	   2,   6, 0Ch, 30h,	30h
		.DB	   1,   6, 0Bh, 2Fh,	2Fh
		.DB	   6,   6,	6, 2Ch,	2Eh
		.DB	   1,   8,	8, 2Dh,	2Dh
		.DB	   2,   8, 0Ah, 2Eh,	2Eh
		.DB	 0Bh, 0Bh, 0Bh, 27h,	2Eh
		.DB	   6, 0Bh, 0Bh, 28h,	28h
		.DB	   6, 0Bh, 0Bh, 2Ch,	2Ch
		.DB	 0Bh,   2,	2, 27h,	28h
		.DB	   1,   2,	8, 29h,	29h
		.DB	 0Bh,   3,	5, 29h,	29h
		.DB	   6,   5,	5, 27h,	28h
		.DB	   2,   3,	8, 2Ah,	2Ah
		.DB	 0Bh,   9,	9, 29h,	2Bh
		.DB	   6,   9,	9, 2Ch,	2Ch
		.DB	 0Bh,   3,	4, 2Bh,	2Bh
		.DB	   1,   2,	3, 2Ch,	2Ch
		.DB	   8,   2,	2, 2Bh,	2Bh
		.DB	   7,   3,	3, 2Dh,	2Dh
		.DB	   6,   4,	4, 2Dh,	2Eh
		.DB	 0Bh,   3,	4, 2Fh,	31h
		.DB	 0Bh,   4,	4, 33h,	35h
		.DB	 0Bh,   5,	5, 33h,	34h
		.DB	 0Bh,   6,	6, 34h,	3Bh
		.DB	   6,   6,	6, 36h,	36h
		.DB	 0Ah,   5,	5, 37h,	37h
		.DB	 0Bh,   2,	2, 34h,	38h
		.DB	 0Bh,   3,	3, 38h,	3Dh
		.DB	 0Bh,   4,	4, 37h,	38h
		.DB	   2,   3,	5, 39h,	39h
		.DB	   2,   1,	2, 3Ch,	3Ch
		.DB	   2,   3,	8, 32h,	32h
		.DB	   6,   8,	8, 33h,	3Ch
		.DB	   2,   5, 15h, 3Dh,	3Dh
		.DB	   6, 14h, 14h, 37h,	3Ch
		.DB	 0Bh, 14h, 14h, 24h,	35h
		.DB	   1, 15h, 15h, 2Ah,	2Ah
		.DB	   2, 14h, 14h, 2Bh,	2Bh
		.DB	 0Bh, 13h, 13h, 34h,	34h
		.DB	   1, 11h, 12h, 34h,	34h
		.DB	   7, 10h, 10h, 34h,	34h
		.DB	 0Bh, 0Ah, 0Eh, 34h,	37h
		.DB	 0Bh, 0Ah, 0Ah, 32h,	33h
		.DB	 0Bh, 0Ch, 0Dh, 33h,	33h
		.DB	   6, 0Ch, 0Ch, 32h,	32h
		.DB	   7, 0Bh, 0Bh, 33h,	33h
		.DB	   1, 0Bh, 0Bh, 35h,	35h
		.DB	   1, 0Eh, 0Eh, 35h,	35h
		.DB	 0Bh, 0Ah, 0Ah, 38h,	38h
		.DB	   1, 0Ah, 0Bh, 39h,	3Bh
		.DB	   5, 0Ah, 0Ah, 3Ah,	3Ah
		.DB	   6, 0Ah, 0Ah, 3Ch,	3Ch
		.DB	   6, 0Eh, 0Eh, 38h,	38h
		.DB	 0Bh, 0Ch, 0Fh, 39h,	3Bh
		.DB	   7, 0Dh, 0Dh, 3Ah,	3Ah
		.DB	 0Bh, 10h, 10h, 3Ah,	3Bh
		.DB	   7, 11h, 11h, 3Bh,	3Bh
		.DB	 0Bh, 10h, 10h, 38h,	38h
		.DB	 0Bh, 11h, 11h, 38h,	39h
		.DB	 0Bh, 12h, 12h, 38h,	3Bh
		.DB	   2, 0Ah, 15h, 36h,	36h
		.DB	   0
;Level1Attrib:	tLevelAttr <   1,    2,	   1,  30h,    1,  2Fh,	   2,  1Ah, 0, 0, \
;			       3,    1,	 3Ch>
Level1Attrib:	.DB	1,    2,	   1,  30h,    1,  2Fh,	   2,  1Ah, 0, 0, 3, 1, 3Ch

Level2:		.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01D4o
		.DB	   1, 15h, 17h,   0,	3Fh
		.DB	   1,   1, 17h, 3Ah,	3Fh
		.DB	   5, 15h, 16h,   8,	39h
		.DB	   1, 15h, 15h, 0Ch,	0Dh
		.DB	   1, 15h, 15h, 12h,	13h
		.DB	   1, 15h, 15h, 18h,	19h
		.DB	   1, 15h, 15h, 1Eh,	1Fh
		.DB	   1, 15h, 15h, 24h,	25h
		.DB	   1, 15h, 15h, 2Ah,	2Bh
		.DB	   1, 15h, 15h, 30h,	31h
		.DB	   1, 15h, 15h, 36h,	37h
		.DB	   2,   4, 14h,   6,	  7
		.DB	   2,   3, 14h, 0Ch,	0Dh
		.DB	   2,   4, 14h, 12h,	13h
		.DB	   2,   3, 14h, 18h,	19h
		.DB	   2,   4, 14h, 1Eh,	1Fh
		.DB	   2,   3, 14h, 24h,	25h
		.DB	   2,   4, 14h, 2Ah,	2Bh
		.DB	   2,   3, 14h, 30h,	31h
		.DB	   2,   4, 14h, 36h,	37h
		.DB	   2,   3,	3,   8,	35h
		.DB	   2,   6,	6,   6,	37h
		.DB	   2,   9,	9,   8,	35h
		.DB	   2, 0Ch, 0Ch,   6,	35h
		.DB	   2, 0Fh, 0Fh,   6,	36h
		.DB	   2, 12h, 12h,   6,	36h
		.DB	   1,   1,	4, 38h,	3Ah
		.DB	 0Ah,   3,	3, 39h,	39h
		.DB	   2,   3,	3, 38h,	38h
		.DB	   2,   1,	3, 3Ah,	3Ah
		.DB	   7,   3,	3,   6,	  7
		.DB	   7,   3,	3, 12h,	13h
		.DB	   7,   3,	3, 1Eh,	1Fh
		.DB	   7,   3,	3, 2Ah,	2Bh
		.DB	   7,   3,	3, 36h,	37h
		.DB	   7,   6,	6, 0Ch,	0Dh
		.DB	   7,   6,	6, 18h,	19h
		.DB	   7,   6,	6, 24h,	25h
		.DB	   7,   6,	6, 30h,	31h
		.DB	   7,   9,	9,   6,	  7
		.DB	   7,   9,	9, 12h,	13h
		.DB	   7,   9,	9, 1Eh,	1Fh
		.DB	   7,   9,	9, 2Ah,	2Bh
		.DB	   7,   9,	9, 36h,	37h
		.DB	   7, 0Ch, 0Ch, 0Ch,	0Dh
		.DB	   7, 0Ch, 0Ch, 18h,	19h
		.DB	   7, 0Ch, 0Ch, 24h,	25h
		.DB	   7, 0Ch, 0Ch, 30h,	31h
		.DB	   7, 0Fh, 0Fh,   6,	  7
		.DB	   7, 0Fh, 0Fh, 12h,	13h
		.DB	   7, 0Fh, 0Fh, 1Eh,	1Fh
		.DB	   7, 0Fh, 0Fh, 2Ah,	2Bh
		.DB	   7, 0Fh, 0Fh, 36h,	37h
		.DB	   7, 12h, 12h, 0Ch,	0Dh
		.DB	   7, 12h, 12h, 18h,	19h
		.DB	   7, 12h, 12h, 24h,	25h
		.DB	   7, 12h, 12h, 30h,	31h
		.DB	   8,   9,	9, 1Eh,	1Eh
		.DB	   0
;Level2Attrib:	tLevelAttr <   7,    4,	   1,  0Dh,    1,  30h,	0, 0, 0, 0,    2, \
;			       1,  3Ah>
Level2Attrib:	.DB	7,    4,	   1,  0Dh,    1,  30h,	0, 0, 0, 0,    2, 1,  3Ah

Level3:		.DB	   1,   1, 17h,   0,	3Fh ; DATA XREF: ROM:01D6o
		.DB	 0Eh,   1,	1, 0Ah,	0Bh
		.DB	 0Eh,   5,	5,   6,	  9
		.DB	 0Eh, 11h, 11h,   6,	  9
		.DB	 0Eh, 15h, 15h,   6,	10h
		.DB	   7, 0Dh, 0Dh,   6,	  9
		.DB	 0Eh,   9,	9, 0Ch,	15h
		.DB	 0Eh,   5,	5, 12h,	1Bh
		.DB	 0Eh,   2,	2, 1Eh,	21h
		.DB	   7,   2,	2, 0Ch,	0Fh
		.DB	   7, 0Dh, 0Dh, 24h,	27h
		.DB	 0Eh, 0Dh, 0Dh, 18h,	1Bh
		.DB	 0Eh, 11h, 11h, 12h,	15h
		.DB	 0Eh, 11h, 11h, 1Ah,	27h
		.DB	   7, 15h, 15h, 18h,	1Bh
		.DB	 0Eh, 15h, 15h, 1Eh,	21h
		.DB	   7,   9,	9, 1Eh,	21h
		.DB	 0Eh,   5,	5, 24h,	27h
		.DB	   7,   2,	2, 2Ah,	2Dh
		.DB	 0Eh,   9,	9, 2Ah,	33h
		.DB	 0Eh, 0Dh, 0Dh, 30h,	33h
		.DB	   7,   5,	5, 30h,	33h
		.DB	 0Eh,   1,	1, 34h,	35h
		.DB	 0Eh, 11h, 11h, 30h,	33h
		.DB	   7, 15h, 15h, 2Ah,	2Dh
		.DB	   7, 15h, 15h, 36h,	39h
		.DB	   2,   7, 15h,   4,	  5
		.DB	   2,   2,	5,   4,	  5
		.DB	   2,   2,	9, 0Ah,	0Bh
		.DB	   2, 0Bh, 0Dh, 0Ah,	0Bh
		.DB	   2, 0Fh, 11h, 0Ah,	0Bh
		.DB	   2, 13h, 15h, 0Ah,	0Bh
		.DB	   2,   2,	5, 10h,	11h
		.DB	   2,   7, 0Dh, 10h,	11h
		.DB	   2, 0Fh, 15h, 10h,	11h
		.DB	   2,   2,	5, 16h,	17h
		.DB	   2,   7, 15h, 16h,	17h
		.DB	   2,   2,	9, 1Ch,	1Dh
		.DB	   2, 0Bh, 15h, 1Ch,	1Dh
		.DB	   2,   2,	5, 22h,	23h
		.DB	   2,   7,	9, 22h,	23h
		.DB	   2, 0Bh, 0Dh, 22h,	23h
		.DB	   2, 0Fh, 11h, 22h,	23h
		.DB	   2, 13h, 15h, 22h,	23h
		.DB	   2,   2, 0Dh, 28h,	29h
		.DB	   2, 0Fh, 15h, 28h,	29h
		.DB	   2,   2,	5, 2Eh,	2Fh
		.DB	   2,   7,	9, 2Eh,	2Fh
		.DB	   2, 0Bh, 11h, 2Eh,	2Fh
		.DB	   2, 13h, 15h, 2Eh,	2Fh
		.DB	   2,   2,	5, 34h,	35h
		.DB	   2,   7, 0Dh, 34h,	35h
		.DB	   2, 0Fh, 15h, 34h,	35h
		.DB	   7, 15h, 15h, 36h,	39h
		.DB	   2,   1, 15h, 3Ah,	3Ah
		.DB	   0
;Level3Attrib:	tLevelAttr <15h, 6, 1, 0Ah, 1, 34h, 0, 0, 0, 0,	2, 1, 3Ah>
Level3Attrib:	.DB	15h, 6, 1, 0Ah, 1, 34h, 0, 0, 0, 0,	2, 1, 3Ah

Level4:		.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01D8o
		.DB	   1, 16h, 17h,   0,	3Fh
		.DB	   1,   1, 17h, 3Ah,	3Fh
		.DB	   1, 0Ah, 0Ah,   0,	3Fh
		.DB	   1, 0Eh, 0Eh,   0,	3Fh
		.DB	   1, 12h, 12h,   0,	3Fh
		.DB	 0Bh,   1,	2,   4,	37h
		.DB	   6,   3,	3, 0Ch,	35h
		.DB	   1,   6,	6,   8,	3Ah
		.DB	   1, 0Bh, 0Ch, 0Ah,	0Bh
		.DB	   1, 0Bh, 15h, 12h,	13h
		.DB	   1, 0Bh, 15h, 22h,	23h
		.DB	   1, 0Bh, 15h, 32h,	33h
		.DB	   1, 0Fh, 15h, 2Ah,	33h
		.DB	   1, 0Ah, 0Ch, 22h,	2Bh
		.DB	   6, 14h, 14h,   4,	  9
		.DB	   6, 10h, 10h,   4,	  9
		.DB	   2, 0Eh, 15h,   6,	  7
		.DB	 0Bh, 0Fh, 11h, 0Ah,	0Bh
		.DB	 0Bh, 13h, 14h, 0Ah,	0Bh
		.DB	   4, 15h, 15h, 0Ah,	0Ah
		.DB	   2, 10h, 15h, 0Eh,	0Fh
		.DB	   3, 15h, 15h, 13h,	13h
		.DB	   7, 11h, 11h, 11h,	11h
		.DB	   5, 0Ah, 0Ah,   2,	  5
		.DB	 1Ah, 0Bh, 0Bh,   2,	  5
		.DB	   1, 0Ch, 0Ch,   0,	  7
		.DB	   1, 0Bh, 0Bh,   6,	  7
		.DB	   2, 0Ah, 0Dh, 0Eh,	0Fh
		.DB	   4, 0Dh, 0Dh, 0Ah,	0Ah
		.DB	   3, 0Dh, 0Dh, 13h,	13h
		.DB	   7,   9,	9,   6,	  9
		.DB	   3,   9,	9, 0Ah,	0Ah
		.DB	   2, 12h, 13h, 14h,	15h
		.DB	   6, 14h, 14h, 16h,	1Fh
		.DB	   7, 13h, 13h, 20h,	20h
		.DB	 0Bh, 15h, 15h, 16h,	23h
		.DB	 0Eh, 0Dh, 0Dh, 12h,	12h
		.DB	 0Eh, 15h, 15h, 12h,	12h
		.DB	   1,   8,	8,   6,	23h
		.DB	   7, 11h, 11h, 18h,	18h
		.DB	 0Bh, 0Eh, 0Eh, 18h,	2Fh
		.DB	   1, 0Ch, 0Dh, 18h,	1Bh
		.DB	 0Bh, 0Dh, 0Dh, 1Ah,	1Bh
		.DB	   1, 0Fh, 12h, 1Ah,	1Bh
		.DB	   6, 0Fh, 0Fh, 1Ch,	21h
		.DB	   5, 10h, 10h, 1Ch,	21h
		.DB	 1Ah, 11h, 11h, 1Ch,	21h
		.DB	   2, 0Ah, 0Bh, 1Ah,	1Bh
		.DB	   4,   9,	9, 1Ah,	1Ah
		.DB	   5, 0Bh, 0Bh, 24h,	29h
		.DB	   6, 0Ah, 0Ah, 26h,	27h
		.DB	   7, 0Dh, 0Dh, 26h,	26h
		.DB	   7, 0Bh, 0Bh, 31h,	31h
		.DB	   2, 0Ch, 0Eh, 30h,	31h
		.DB	   7, 0Dh, 0Dh, 37h,	37h
		.DB	   2, 0Eh, 15h, 38h,	39h
		.DB	   1, 11h, 11h, 36h,	37h
		.DB	 0Bh, 10h, 11h, 2Eh,	33h
		.DB	   8, 10h, 10h, 2Eh,	2Eh
		.DB	   7, 10h, 10h, 2Fh,	2Fh
		.DB	   2, 11h, 15h, 2Ch,	2Dh
		.DB	   2, 11h, 15h, 30h,	31h
		.DB	 0Bh, 15h, 15h, 2Ah,	2Bh
		.DB	   4, 15h, 15h, 33h,	33h
		.DB	 0Eh, 15h, 15h, 32h,	32h
		.DB	   6, 0Fh, 0Fh, 24h,	29h
		.DB	   5, 10h, 10h, 24h,	29h
		.DB	 1Ah, 11h, 11h, 24h,	29h
		.DB	   6,   8,	8, 14h,	19h
		.DB	   6,   8,	8, 24h,	25h
		.DB	   6,   8,	8, 28h,	29h
		.DB	   4,   9,	9, 2Ah,	2Ah
		.DB	 0Bh, 0Dh, 0Dh, 22h,	23h
		.DB	   6,   6,	6, 14h,	19h
		.DB	   6,   6,	6, 24h,	29h
		.DB	   1,   8,	8, 2Ah,	35h
		.DB	 0Bh,   7,	7, 34h,	35h
		.DB	   2,   1,	9, 3Ah,	3Ah
		.DB	   2,   2,	9, 36h,	37h
		.DB	   1,   1,	8, 38h,	39h
		.DB	 0Ah,   9,	9, 38h,	38h
		.DB	   4,   7,	7,   8,	  8
		.DB	   1,   3,	5, 0Ah,	0Bh
		.DB	   7,   5,	5, 0Ch,	11h
		.DB	 0Bh,   3,	5, 12h,	13h
		.DB	   1,   4,	4, 12h,	13h
		.DB	   7,   5,	5, 14h,	14h
		.DB	   2,   2,	5, 18h,	19h
		.DB	 0Bh,   5,	5, 1Ah,	25h
		.DB	   7,   5,	5, 1Ch,	21h
		.DB	   1,   3,	4, 1Ah,	1Bh
		.DB	   1,   4,	5, 22h,	23h
		.DB	 0Bh,   3,	3, 22h,	23h
		.DB	   7,   4,	4, 24h,	24h
		.DB	   2,   2,	5, 28h,	29h
		.DB	   1,   3,	4, 2Ah,	2Bh
		.DB	 0Bh,   5,	5, 2Ah,	2Bh
		.DB	   7,   5,	5, 2Ch,	35h
		.DB	 0Bh,   3,	3, 32h,	33h
		.DB	   1,   4,	5, 32h,	33h
		.DB	 0Eh,   7,	7, 34h,	35h
		.DB	   0
;Level4Attrib:	tLevelAttr < 15h,    4,	   4,  16h,    7,  34h,	0, 0, 0, 0,    2, \
;			       1,  3Ah>
Level4Attrib:	.DB	15h,    4,	   4,  16h,    7,  34h,	0, 0, 0, 0,    2, 1,  3Ah

Level5:		.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01DAo
		.DB	 0Bh, 16h, 17h,   4,	3Bh
		.DB	   1,   1, 17h, 3Ch,	3Fh
		.DB	   1,   7, 10h,   8,	37h
		.DB	   5,   7,	7, 0Ch,	11h
		.DB	 19h,   8,	8, 0Ah,	13h
		.DB	 19h,   9, 0Fh, 0Ah,	0Bh
		.DB	 19h,   9, 0Fh, 12h,	13h
		.DB	 19h, 0Ch, 0Dh, 0Ah,	13h
		.DB	   5,   7,	7, 18h,	1Dh
		.DB	 19h,   8,	8, 16h,	1Fh
		.DB	 19h,   9,	9, 1Eh,	1Fh
		.DB	 19h,   8, 0Bh, 16h,	17h
		.DB	 19h, 0Bh, 0Bh, 16h,	1Fh
		.DB	 19h, 0Bh, 0Eh, 1Eh,	1Fh
		.DB	 19h, 0Dh, 0Eh, 16h,	17h
		.DB	 19h, 0Eh, 0Fh, 18h,	1Dh
		.DB	   5,   7,	7, 24h,	29h
		.DB	 19h,   8,	9, 2Ah,	2Bh
		.DB	 19h,   8,	8, 22h,	29h
		.DB	 19h,   9, 0Eh, 22h,	23h
		.DB	 19h, 0Eh, 0Fh, 24h,	29h
		.DB	 19h, 0Dh, 0Eh, 2Ah,	2Bh
		.DB	   5,   7,	7, 2Eh,	2Fh
		.DB	 19h,   8, 0Fh, 2Eh,	2Fh
		.DB	   5,   7,	7, 34h,	35h
		.DB	 19h,   8, 0Fh, 34h,	35h
		.DB	   6,   3,	5,   6,	39h
		.DB	   7,   4,	4,   6,	39h
		.DB	   1,   1,	3, 1Eh,	23h
		.DB	 0Ah,   2,	2, 1Eh,	1Eh
		.DB	 0Eh,   2,	2, 1Fh,	1Fh
		.DB	   2,   1,	2, 20h,	20h
		.DB	   2,   3, 12h,   4,	  5
		.DB	   7,   6, 11h,   6,	  6
		.DB	   7, 11h, 11h,   6,	39h
		.DB	   7,   6, 11h, 39h,	39h
		.DB	   2,   3, 11h, 3Ah,	3Bh
		.DB	   8, 11h, 11h, 1Ah,	1Ah
		.DB	   2, 14h, 14h,   4,	  5
		.DB	   2, 13h, 13h,   6,	  7
		.DB	   2, 15h, 15h,   6,	  7
		.DB	   2, 12h, 12h,   8,	  9
		.DB	   2, 14h, 14h,   8,	  9
		.DB	   2, 13h, 13h, 0Ah,	0Bh
		.DB	   2, 15h, 15h, 0Ah,	0Bh
		.DB	   2, 12h, 12h, 0Ch,	0Dh
		.DB	   2, 14h, 14h, 0Ch,	0Dh
		.DB	   2, 13h, 13h, 0Eh,	0Fh
		.DB	   2, 15h, 15h, 0Eh,	0Fh
		.DB	   2, 12h, 12h, 10h,	11h
		.DB	   2, 14h, 14h, 10h,	11h
		.DB	   2, 13h, 13h, 12h,	13h
		.DB	   2, 15h, 15h, 12h,	13h
		.DB	   2, 12h, 12h, 14h,	15h
		.DB	   2, 14h, 14h, 14h,	15h
		.DB	   2, 13h, 13h, 16h,	17h
		.DB	   2, 15h, 15h, 16h,	17h
		.DB	   2, 12h, 12h, 18h,	19h
		.DB	   2, 14h, 14h, 18h,	19h
		.DB	   2, 13h, 13h, 1Ah,	1Bh
		.DB	   2, 15h, 15h, 1Ah,	1Bh
		.DB	   2, 12h, 12h, 1Ch,	1Dh
		.DB	   2, 14h, 14h, 1Ch,	1Dh
		.DB	   2, 13h, 13h, 1Eh,	1Fh
		.DB	   2, 15h, 15h, 1Eh,	1Fh
		.DB	   2, 12h, 12h, 20h,	21h
		.DB	   2, 14h, 14h, 20h,	21h
		.DB	   2, 13h, 13h, 22h,	23h
		.DB	   2, 15h, 15h, 22h,	23h
		.DB	   2, 12h, 12h, 24h,	25h
		.DB	   2, 14h, 14h, 24h,	25h
		.DB	   2, 13h, 13h, 26h,	27h
		.DB	   2, 15h, 15h, 26h,	27h
		.DB	   2, 12h, 12h, 28h,	29h
		.DB	   2, 14h, 14h, 28h,	29h
		.DB	   2, 13h, 13h, 2Ah,	2Bh
		.DB	   2, 15h, 15h, 2Ah,	2Bh
		.DB	   2, 12h, 12h, 2Ch,	2Dh
		.DB	   2, 14h, 14h, 2Ch,	2Dh
		.DB	   2, 13h, 13h, 2Eh,	2Fh
		.DB	   2, 15h, 15h, 2Eh,	2Fh
		.DB	   2, 12h, 12h, 30h,	31h
		.DB	   2, 14h, 14h, 30h,	31h
		.DB	   2, 13h, 13h, 32h,	33h
		.DB	   2, 15h, 15h, 32h,	33h
		.DB	   2, 12h, 12h, 34h,	35h
		.DB	   2, 14h, 14h, 34h,	35h
		.DB	   2, 13h, 13h, 36h,	37h
		.DB	   2, 15h, 15h, 36h,	37h
		.DB	   2, 12h, 12h, 38h,	39h
		.DB	   2, 14h, 14h, 38h,	39h
		.DB	   2, 13h, 13h, 3Ah,	3Bh
		.DB	   2, 15h, 15h, 3Ah,	3Bh
		.DB	   0
;Level5Attrib:	tLevelAttr < 15h,    4,	0,    7, 0,  38h, 0, 0,	0, 0,	 2,    1, \
;			     20h>
Level5Attrib:	.DB	15h,    4,	0,    7, 0,  38h, 0, 0,	0, 0,	 2,    1, 20h

Level6:		.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01DCo
		.DB	   1, 16h, 17h,   0,	3Fh
		.DB	   1,   1, 17h, 3Ch,	3Fh
		.DB	   5, 16h, 16h, 1Ch,	23h
		.DB	   6,   2,	2, 18h,	27h
		.DB	   2,   2, 15h, 1Ah,	1Bh
		.DB	   2,   2, 15h, 24h,	25h
		.DB	   4, 15h, 15h,   8,	  8
		.DB	   4, 15h, 15h, 17h,	17h
		.DB	   4, 15h, 15h, 28h,	28h
		.DB	   4, 15h, 15h, 37h,	37h
		.DB	 0Bh,   2,	2,   8,	17h
		.DB	 0Bh,   3,	3,   8,	  9
		.DB	 0Bh,   3,	3, 16h,	17h
		.DB	 0Bh,   4,	4, 0Ah,	15h
		.DB	 0Bh,   5,	5,   8,	  9
		.DB	 0Bh,   5,	5, 16h,	17h
		.DB	 0Bh,   6,	6, 0Ah,	15h
		.DB	 0Bh,   7,	7,   8,	  9
		.DB	 0Bh,   7,	7, 16h,	17h
		.DB	 0Bh,   8,	8, 0Ah,	15h
		.DB	 0Bh,   9,	9,   8,	  9
		.DB	 0Bh,   9,	9, 16h,	17h
		.DB	 0Bh, 0Ah, 0Ah, 0Ah,	15h
		.DB	 0Bh, 0Bh, 0Bh,   8,	  9
		.DB	 0Bh, 0Bh, 0Bh, 16h,	17h
		.DB	 0Bh, 0Ch, 0Ch, 0Ah,	15h
		.DB	 0Bh, 0Fh, 0Fh,   8,	  9
		.DB	 0Bh, 0Fh, 0Fh, 16h,	17h
		.DB	 0Bh, 0Dh, 0Dh,   8,	  9
		.DB	 0Bh, 0Dh, 0Dh, 16h,	17h
		.DB	 0Bh, 0Eh, 0Eh, 0Ah,	15h
		.DB	 0Bh, 10h, 10h, 0Ah,	15h
		.DB	 0Bh, 12h, 12h, 0Ah,	15h
		.DB	 0Bh, 11h, 11h,   8,	  9
		.DB	 0Bh, 11h, 11h, 16h,	17h
		.DB	 0Bh, 13h, 13h,   8,	  9
		.DB	 0Bh, 13h, 13h, 16h,	17h
		.DB	 0Bh, 14h, 14h,   8,	17h
		.DB	   7,   3,	3, 0Eh,	11h
		.DB	   7,   5,	5, 0Eh,	11h
		.DB	   7,   7,	7, 0Eh,	11h
		.DB	   7,   9,	9, 0Eh,	11h
		.DB	   7, 0Bh, 0Bh, 0Eh,	11h
		.DB	   7, 0Dh, 0Dh, 0Eh,	11h
		.DB	   7, 0Fh, 0Fh, 0Eh,	11h
		.DB	   7, 11h, 11h, 0Eh,	11h
		.DB	   7, 13h, 13h, 0Eh,	11h
		.DB	   8, 13h, 13h, 0Fh,	0Fh
		.DB	 0Bh,   2,	2, 28h,	37h
		.DB	 0Bh,   4,	4, 2Ah,	35h
		.DB	 0Bh,   6,	6, 2Ah,	35h
		.DB	 0Bh,   8,	8, 2Ah,	35h
		.DB	 0Bh, 0Ah, 0Ah, 2Ah,	35h
		.DB	 0Bh, 0Ch, 0Ch, 2Ah,	35h
		.DB	 0Bh, 0Eh, 0Eh, 2Ah,	35h
		.DB	 0Bh, 10h, 10h, 2Ah,	35h
		.DB	 0Bh, 12h, 12h, 2Ah,	35h
		.DB	 0Bh, 14h, 14h, 28h,	37h
		.DB	 0Bh,   3,	3, 28h,	29h
		.DB	 0Bh,   5,	5, 28h,	29h
		.DB	 0Bh,   7,	7, 28h,	29h
		.DB	 0Bh,   9,	9, 28h,	29h
		.DB	 0Bh, 0Bh, 0Bh, 28h,	29h
		.DB	 0Bh, 0Dh, 0Dh, 28h,	29h
		.DB	 0Bh, 0Fh, 0Fh, 28h,	29h
		.DB	 0Bh, 11h, 11h, 28h,	29h
		.DB	 0Bh, 13h, 13h, 28h,	29h
		.DB	 0Bh,   3,	3, 36h,	37h
		.DB	 0Bh,   5,	5, 36h,	37h
		.DB	 0Bh,   7,	7, 36h,	37h
		.DB	 0Bh,   9,	9, 36h,	37h
		.DB	 0Bh, 0Bh, 0Bh, 36h,	37h
		.DB	 0Bh, 0Dh, 0Dh, 36h,	37h
		.DB	 0Bh, 0Fh, 0Fh, 36h,	37h
		.DB	 0Bh, 11h, 11h, 36h,	37h
		.DB	 0Bh, 13h, 13h, 36h,	37h
		.DB	   7,   3,	3, 2Eh,	31h
		.DB	   7,   5,	5, 2Eh,	31h
		.DB	   7,   7,	7, 2Eh,	31h
		.DB	   7,   9,	9, 2Eh,	31h
		.DB	   7, 0Bh, 0Bh, 2Eh,	31h
		.DB	   7, 0Dh, 0Dh, 2Eh,	31h
		.DB	   7, 0Fh, 0Fh, 2Eh,	31h
		.DB	   7, 11h, 11h, 2Eh,	31h
		.DB	   7, 13h, 13h, 2Eh,	31h
		.DB	   1, 14h, 14h, 3Ah,	3Bh
		.DB	 0Ah, 15h, 15h, 3Ah,	3Ah
		.DB	   2,   1, 15h, 3Ch,	3Ch
		.DB	   0
;Level6Attrib:	tLevelAttr <   5,    4,	0,  11h, 0,  2Eh, 0, 0,	0, 0,	 2,    1, \
;			     3Ch>
Level6Attrib:	.DB	5,    4, 0,  11h, 0,  2Eh, 0, 0,	0, 0,	 2,    1, 3Ch

Level7:		.DB	   1,   1, 17h,   0,	  5 ; DATA XREF: ROM:01DEo
		.DB	   1, 16h, 17h,   0,	3Fh
		.DB	   1,   1, 17h, 3Ch,	3Fh
		.DB	   5, 16h, 16h,   6,	13h
		.DB	   7, 14h, 14h,   4,	  5
		.DB	   6, 15h, 15h,   6,	13h
		.DB	   2, 15h, 15h, 14h,	15h
		.DB	   5, 16h, 16h, 2Eh,	3Bh
		.DB	   2, 15h, 15h, 2Ch,	2Dh
		.DB	   6, 15h, 15h, 2Eh,	31h
		.DB	   2, 0Ch, 14h, 30h,	31h
		.DB	   6, 0Ch, 0Ch, 32h,	39h
		.DB	   2,   2, 0Bh, 38h,	39h
		.DB	   6,   2,	2, 24h,	37h
		.DB	 0Bh,   2, 16h, 1Eh,	23h
		.DB	 0Bh,   8, 0Ah, 14h,	2Dh
		.DB	   7,   3, 15h, 20h,	21h
		.DB	   7,   9,	9, 16h,	2Bh
		.DB	   6,   8,	8, 20h,	21h
		.DB	   6, 0Ah, 0Ah, 20h,	21h
		.DB	   8, 0Eh, 0Eh, 20h,	20h
		.DB	   6, 0Eh, 0Eh, 34h,	35h
		.DB	   1, 0Eh, 0Eh, 36h,	39h
		.DB	 0Bh, 0Fh, 0Fh, 36h,	37h
		.DB	 0Ah, 0Fh, 0Fh, 39h,	39h
		.DB	   1, 10h, 10h, 34h,	39h
		.DB	   6, 10h, 10h, 3Ah,	3Bh
		.DB	   2,   1, 10h, 3Ch,	3Ch
		.DB	   6, 0Ah, 0Ah, 2Eh,	33h
		.DB	   0
;Level7Attrib:	tLevelAttr < 15h,  16h,	0,  14h, 0,  2Dh, 0, 0,	0, 0,	 2,    1, \
;			     3Ch>
Level7Attrib:	.DB	15h,  16h, 0,  14h, 0,  2Dh, 0, 0, 0, 0,  2, 1, 3Ch

Level8:		.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01E0o
		.DB	   1, 17h, 17h,   0,	3Fh
		.DB	   1,   1, 17h, 3Bh,	3Fh
		.DB	   2,   1, 16h, 3Ah,	3Ah
		.DB	   1,   1, 15h, 38h,	39h
		.DB	   2, 14h, 16h,   6,	  7
		.DB	   2,   9, 14h,   4,	  5
		.DB	   2,   5,	9,   6,	  7
		.DB	   7,   4,	4,   7,	  7
		.DB	   1, 0Fh, 11h,   6,	11h
		.DB	   1, 12h, 16h, 0Ch,	11h
		.DB	   5, 0Fh, 0Fh,   8,	0Fh
		.DB	 1Ah, 10h, 10h,   8,	0Fh
		.DB	 1Ch, 11h, 16h, 0Eh,	0Eh
		.DB	 1Dh, 11h, 16h, 0Fh,	0Fh
		.DB	   1, 0Eh, 0Eh, 0Ah,	0Dh
		.DB	   6, 0Eh, 0Eh, 0Eh,	0Fh
		.DB	   6, 0Fh, 0Fh, 12h,	13h
		.DB	   2,   3,	4, 0Bh,	0Bh
		.DB	 0Bh,   4,	4, 0Ch,	19h
		.DB	 0Bh,   6,	6, 10h,	19h
		.DB	   6,   6,	6, 12h,	13h
		.DB	   8,   5,	5, 10h,	10h
		.DB	   7,   5,	5, 14h,	14h
		.DB	   7,   5,	5, 19h,	19h
		.DB	   6,   8,	8,   8,	19h
		.DB	   1,   4,	6, 1Ah,	1Bh
		.DB	 0Bh, 0Ah, 0Ah, 0Ah,	1Dh
		.DB	   1, 0Bh, 0Ch, 0Ch,	27h
		.DB	   1,   4,	4, 1Ch,	23h
		.DB	   1,   5,	6, 22h,	23h
		.DB	   1,   6,	8, 1Eh,	1Fh
		.DB	   1,   8,	8, 1Eh,	25h
		.DB	   6,   8,	8, 26h,	27h
		.DB	   2,   6,	9, 1Ch,	1Dh
		.DB	   2,   6,	7, 20h,	21h
		.DB	 0Bh,   4,	4, 24h,	27h
		.DB	   1,   6,	6, 24h,	25h
		.DB	   2,   3,	7, 28h,	29h
		.DB	   1,   7,	7, 2Ah,	2Dh
		.DB	   2,   5,	6, 2Ch,	2Dh
		.DB	   2,   4,	5, 2Eh,	2Fh
		.DB	   2,   3,	4, 30h,	31h
		.DB	   2,   4,	5, 32h,	33h
		.DB	   2,   5,	5, 34h,	35h
		.DB	   1,   6,	6, 34h,	37h
		.DB	   2,   7, 14h, 36h,	37h
		.DB	   6,   9,	9, 2Ch,	35h
		.DB	   1, 0Bh, 0Ch, 2Eh,	33h
		.DB	   5, 0Bh, 0Bh, 30h,	31h
		.DB	   7, 0Ah, 0Ah, 22h,	25h
		.DB	 0Bh, 0Ah, 0Ah, 26h,	27h
		.DB	   6, 0Ah, 0Ah, 28h,	29h
		.DB	   6, 0Bh, 0Bh, 1Eh,	21h
		.DB	   5, 0Ch, 0Ch, 1Eh,	21h
		.DB	   5, 0Ch, 0Ch, 24h,	29h
		.DB	   1, 0Dh, 0Dh, 1Ah,	2Ah
		.DB	   1, 0Eh, 0Eh, 1Ch,	27h
		.DB	   1, 0Ah, 0Ch, 2Ah,	2Bh
		.DB	 1Ah, 0Dh, 0Dh, 20h,	27h
		.DB	 0Bh, 0Eh, 0Eh, 28h,	29h
		.DB	 0Bh, 0Fh, 0Fh, 20h,	25h
		.DB	   1, 0Fh, 10h, 2Ah,	31h
		.DB	   2, 0Fh, 10h, 2Ch,	2Fh
		.DB	 0Bh, 0Eh, 0Eh, 2Ch,	2Dh
		.DB	 0Bh, 0Fh, 0Fh, 30h,	31h
		.DB	 0Bh, 10h, 10h, 2Eh,	2Fh
		.DB	   6, 0Fh, 11h, 32h,	33h
		.DB	   7, 0Eh, 0Eh, 32h,	33h
		.DB	   7, 10h, 10h, 32h,	33h
		.DB	   5, 15h, 15h, 12h,	13h
		.DB	 1Ah, 16h, 16h, 12h,	13h
		.DB	   6, 11h, 11h, 14h,	1Fh
		.DB	   2, 10h, 11h, 24h,	25h
		.DB	   1, 10h, 10h, 1Eh,	23h
		.DB	   2, 10h, 11h, 20h,	21h
		.DB	   2, 10h, 10h, 1Ch,	1Dh
		.DB	   7, 10h, 10h, 14h,	1Bh
		.DB	   1, 15h, 16h, 14h,	16h
		.DB	 0Ah, 14h, 14h, 16h,	16h
		.DB	   1, 12h, 13h, 16h,	17h
		.DB	   1, 13h, 13h, 18h,	1Fh
		.DB	   1, 15h, 15h, 1Ah,	38h
		.DB	   1, 14h, 14h, 1Ah,	1Bh
		.DB	   7, 14h, 14h, 1Ch,	1Ch
		.DB	 0Bh, 12h, 14h, 20h,	31h
		.DB	   6, 12h, 12h, 22h,	23h
		.DB	   2, 13h, 13h, 20h,	21h
		.DB	   2, 14h, 14h, 22h,	23h
		.DB	   2, 13h, 13h, 24h,	25h
		.DB	   6, 12h, 12h, 26h,	27h
		.DB	   2, 14h, 14h, 26h,	27h
		.DB	   2, 13h, 13h, 28h,	29h
		.DB	   6, 12h, 12h, 2Ah,	2Bh
		.DB	   2, 14h, 14h, 2Ah,	2Bh
		.DB	   2, 13h, 13h, 2Ch,	2Dh
		.DB	   6, 12h, 12h, 2Eh,	2Fh
		.DB	   2, 14h, 14h, 2Eh,	2Fh
		.DB	   2, 13h, 13h, 30h,	31h
		.DB	   2, 14h, 14h, 32h,	33h
		.DB	 0Bh, 13h, 13h, 32h,	33h
		.DB	 0Bh, 10h, 10h, 26h,	27h
		.DB	   0
;Level8Attrib:	tLevelAttr < 15h,    4,	   7,  25h,  14h,  1Eh,	0, 0, 0, 0,    2, \
;			       1,  3Ah>
Level8Attrib:	.DB	 15h, 4, 7, 25h, 14h, 1Eh, 0, 0, 0, 0, 2, 1, 3Ah

Level9:		.DB	   1,   1, 17h,   0,	3Fh ; DATA XREF: ROM:01E2o
		.DB	 18h,   5, 0Bh,   2,	  5
		.DB	 0Bh,   1,	1,   2,	17h
		.DB	 18h,   2,	4,   2,	  3
		.DB	 0Eh,   3,	3,   6,	0Fh
		.DB	   7,   3,	3,   6,	  6
		.DB	   7,   3,	3, 0Fh,	0Fh
		.DB	   2,   4, 0Dh,   8,	  9
		.DB	 0Eh, 0Dh, 0Dh,   4,	  7
		.DB	   2, 0Eh, 15h,   4,	  5
		.DB	 0Eh, 15h, 15h,   6,	0Fh
		.DB	   2, 14h, 15h, 10h,	11h
		.DB	   7, 13h, 13h, 10h,	11h
		.DB	 0Eh, 0Fh, 0Fh,   6,	1Bh
		.DB	   2,   5, 0Fh, 16h,	17h
		.DB	 0Eh,   9,	9, 0Ah,	15h
		.DB	 18h, 0Bh, 0Dh, 0Ch,	13h
		.DB	 18h,   5,	7, 0Ch,	13h
		.DB	 18h,   2,	4, 12h,	13h
		.DB	 18h,   2,	2, 14h,	17h
		.DB	 18h,   6, 0Dh, 1Ah,	1Bh
		.DB	 18h, 11h, 13h,   8,	0Dh
		.DB	 18h, 11h, 11h, 0Eh,	21h
		.DB	 18h, 0Fh, 10h, 1Eh,	21h
		.DB	 0Eh,   4,	4, 16h,	1Fh
		.DB	   2,   4,	4, 1Ah,	1Bh
		.DB	 0Eh,   1,	3, 1Ah,	1Bh
		.DB	   2,   5, 0Dh, 1Eh,	1Fh
		.DB	 0Eh,   9,	9, 20h,	27h
		.DB	   7,   9,	9, 28h,	28h
		.DB	 0Eh, 0Dh, 0Dh, 20h,	27h
		.DB	   7, 0Dh, 0Dh, 27h,	27h
		.DB	 0Eh, 13h, 13h, 18h,	31h
		.DB	   5, 14h, 14h, 18h,	19h
		.DB	   2, 0Eh, 13h, 24h,	25h
		.DB	   7, 13h, 13h, 1Ah,	1Ah
		.DB	 0Eh, 14h, 14h, 30h,	3Bh
		.DB	   2, 14h, 14h, 30h,	31h
		.DB	   2, 0Fh, 14h, 3Ah,	3Bh
		.DB	 0Eh, 0Eh, 0Eh, 3Ah,	3Dh
		.DB	   8, 0Eh, 0Eh, 3Dh,	3Dh
		.DB	   2, 10h, 13h, 2Eh,	2Fh
		.DB	 0Eh, 0Fh, 0Fh, 2Eh,	31h
		.DB	   2, 0Ah, 0Fh, 32h,	33h
		.DB	 0Eh,   9,	9, 32h,	3Bh
		.DB	   5, 0Ah, 0Ah, 3Ah,	3Bh
		.DB	   7,   9,	9, 39h,	39h
		.DB	   2,   6,	9, 30h,	31h
		.DB	 0Eh,   5,	5, 30h,	3Bh
		.DB	 0Eh,   3,	3, 28h,	2Fh
		.DB	 0Eh,   1,	2, 28h,	29h
		.DB	   2,   4,	5, 2Eh,	2Fh
		.DB	 0Ah,   5,	5, 34h,	34h
		.DB	   2,   1,	5, 39h,	39h
		.DB	 18h, 12h, 16h, 14h,	15h
		.DB	 18h, 16h, 16h, 16h,	3Dh
		.DB	 18h, 15h, 15h, 1Ch,	2Dh
		.DB	 18h,   2,	2, 1Eh,	25h
		.DB	 0Bh,   1,	1, 1Eh,	25h
		.DB	 18h,   3,	7, 22h,	25h
		.DB	 18h,   5,	7, 26h,	2Bh
		.DB	 18h,   7, 0Bh, 2Ch,	2Dh
		.DB	 18h, 0Bh, 0Bh, 22h,	2Fh
		.DB	 18h, 0Ch, 0Dh, 2Ah,	2Fh
		.DB	 18h, 0Eh, 11h, 2Ah,	2Bh
		.DB	 18h, 0Fh, 11h, 28h,	29h
		.DB	 0Bh,   1,	1, 2Ch,	36h
		.DB	 18h,   2,	3, 32h,	36h
		.DB	 0Bh,   1,	1, 3Ch,	3Dh
		.DB	 18h,   2,	3, 3Ch,	3Dh
		.DB	 18h,   7,	7, 34h,	3Dh
		.DB	 18h, 0Bh, 12h, 36h,	37h
		.DB	 18h, 0Ch, 0Ch, 38h,	3Dh
		.DB	 18h, 11h, 11h, 32h,	35h
		.DB	 18h, 12h, 12h, 34h,	37h
		.DB	   0
;Level9Attrib:	tLevelAttr < 15h,    6,	0,  1Ah, 0,  28h, 0, 0,	0, 0,	 2,    1, \
;			     39h>
Level9Attrib:	.DB	15h, 6, 0, 1Ah, 0,  28h, 0, 0,	0, 0, 2, 1, 39h

Level10:	.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01E4o
		.DB	   1, 16h, 17h,   0,	3Fh
		.DB	   1,   1, 15h, 3Ch,	3Fh
		.DB	 1Ah, 16h, 16h, 14h,	27h
		.DB	 1Ah, 16h, 16h, 2Ch,	33h
		.DB	   1, 15h, 15h, 12h,	3Fh
		.DB	   5, 15h, 15h, 14h,	27h
		.DB	   5, 15h, 15h, 2Ch,	33h
		.DB	 0Bh,   1,	1,   6,	1Dh
		.DB	 0Bh,   1,	1, 20h,	3Bh
		.DB	 0Bh, 13h, 13h,   6,	23h
		.DB	   6, 13h, 13h, 18h,	1Bh
		.DB	   6, 13h, 13h, 24h,	27h
		.DB	 0Bh, 11h, 12h,   6,	0Bh
		.DB	 0Bh, 0Dh, 10h,   6,	  9
		.DB	 0Bh,   5, 0Ch,   6,	  7
		.DB	 0Bh, 11h, 11h, 0Eh,	25h
		.DB	   6, 11h, 11h, 18h,	19h
		.DB	   2, 11h, 15h, 10h,	11h
		.DB	   1, 0Eh, 0Fh, 0Ch,	11h
		.DB	   5, 0Eh, 0Eh, 0Eh,	0Fh
		.DB	 0Bh, 0Ah, 0Dh, 0Ch,	0Dh
		.DB	   6, 0Ah, 0Ah,   8,	0Bh
		.DB	 0Bh, 0Eh, 0Fh, 12h,	17h
		.DB	   2, 0Eh, 10h, 14h,	15h
		.DB	 0Bh,   3,	3, 0Ch,	2Dh
		.DB	 0Bh,   5,	5, 0Ch,	0Dh
		.DB	 0Bh,   8,	8, 0Ch,	0Dh
		.DB	   6,   4,	4,   8,	  9
		.DB	   2,   3,	8, 0Ah,	0Bh
		.DB	   6,   8,	8, 0Eh,	0Fh
		.DB	   2,   8, 0Dh, 10h,	11h
		.DB	 0Bh, 0Bh, 0Bh, 12h,	17h
		.DB	 0Bh, 0Ch, 0Ch, 16h,	17h
		.DB	   6,   9,	9, 12h,	13h
		.DB	 0Bh,   9,	9, 14h,	1Bh
		.DB	 0Bh, 0Ah, 0Ch, 1Ah,	1Bh
		.DB	 0Bh, 0Ch, 0Ch, 1Ch,	1Fh
		.DB	 0Bh, 0Dh, 0Dh, 1Eh,	1Fh
		.DB	   6, 0Eh, 0Eh, 18h,	19h
		.DB	 0Bh, 0Eh, 0Eh, 1Ah,	1Bh
		.DB	 0Bh, 0Fh, 0Fh, 1Ah,	29h
		.DB	   6, 0Fh, 0Fh, 20h,	21h
		.DB	 0Bh,   5,	5, 10h,	1Bh
		.DB	   2,   3,	4, 1Ah,	1Bh
		.DB	 0Bh,   5,	5, 1Eh,	1Fh
		.DB	 0Bh,   7,	7, 14h,	35h
		.DB	 0Bh,   8, 0Ah, 1Eh,	1Fh
		.DB	   6,   7,	7, 12h,	13h
		.DB	   6,   7,	7, 1Ch,	1Dh
		.DB	   6,   7,	7, 20h,	21h
		.DB	   2,   7,	8, 2Ch,	2Dh
		.DB	   6,   7,	7, 2Eh,	33h
		.DB	 0Bh,   5,	5, 24h,	33h
		.DB	 0Bh,   6,	6, 2Ah,	2Bh
		.DB	   2,   5,	6, 22h,	23h
		.DB	   2,   4,	5, 2Ah,	2Bh
		.DB	   6,   5,	5, 2Eh,	2Fh
		.DB	 0Bh,   9,	9, 24h,	3Bh
		.DB	   2,   9, 0Ah, 22h,	23h
		.DB	   1, 0Bh, 0Dh, 22h,	2Bh
		.DB	   6, 0Bh, 0Bh, 24h,	27h
		.DB	   5, 0Ch, 0Ch, 24h,	29h
		.DB	   6,   9,	9, 2Eh,	2Fh
		.DB	   6,   9,	9, 32h,	33h
		.DB	 0Bh, 0Bh, 0Bh, 28h,	2Dh
		.DB	 0Bh, 0Bh, 0Eh, 2Eh,	31h
		.DB	   6, 0Bh, 0Bh, 2Eh,	2Fh
		.DB	   6, 0Bh, 0Bh, 32h,	33h
		.DB	 0Bh, 0Bh, 0Ch, 34h,	37h
		.DB	 0Bh, 0Eh, 11h, 34h,	37h
		.DB	   2, 0Bh, 14h, 38h,	39h
		.DB	 0Bh, 10h, 10h, 28h,	31h
		.DB	   6, 10h, 10h, 2Ah,	2Dh
		.DB	   1, 12h, 13h, 28h,	29h
		.DB	   2, 12h, 14h, 2Ah,	2Bh
		.DB	   6, 12h, 12h, 2Ch,	2Dh
		.DB	 0Bh, 12h, 12h, 2Eh,	2Fh
		.DB	 0Bh, 13h, 14h, 2Eh,	31h
		.DB	   6, 13h, 13h, 32h,	33h
		.DB	 0Bh, 13h, 14h, 34h,	35h
		.DB	 0Bh,   2,	3, 30h,	31h
		.DB	   2,   3,	4, 32h,	33h
		.DB	 0Bh,   3,	4, 34h,	3Bh
		.DB	 0Bh,   5,	7, 38h,	39h
		.DB	   2,   4,	6, 36h,	37h
		.DB	 0Bh,   5,	5, 3Ah,	3Bh
		.DB	   2,   1,	2, 39h,	39h
		.DB	 0Ah,   2,	2, 34h,	34h
		.DB	   7,   4,	4,   6,	  7
		.DB	   7, 0Ch, 0Ch,   8,	  9
		.DB	   7, 10h, 10h, 0Ah,	0Bh
		.DB	   7, 0Ah, 0Ah, 16h,	17h
		.DB	   7, 12h, 12h, 1Eh,	1Eh
		.DB	   7, 14h, 14h, 28h,	29h
		.DB	   7, 0Ch, 0Ch, 2Eh,	2Fh
		.DB	   7,   2,	2, 2Ch,	2Ch
		.DB	   7,   4,	4, 16h,	17h
		.DB	   7,   4,	4, 3Ah,	3Bh
		.DB	   8,   4,	4, 16h,	16h
		.DB	   0
;Level10Attrib:	tLevelAttr <   1,    4,	   1,  1Eh, 0, 0, 0, 0,	0, 0,	 1, 0,	39h>
Level10Attrib:	.DB	   1,    4,	   1,  1Eh, 0, 0, 0, 0,	0, 0,	 1, 0,	39h

Level11:	.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01E6o
		.DB	   1, 17h, 17h,   0,	3Fh
		.DB	 0Bh, 16h, 16h,   4,	0Bh
		.DB	   1,   1, 16h, 3Ch,	3Fh
		.DB	   5, 16h, 16h, 0Ch,	3Bh
		.DB	   2, 14h, 15h, 0Ah,	0Bh
		.DB	   6, 14h, 14h, 0Ch,	15h
		.DB	   2, 14h, 14h, 16h,	17h
		.DB	   6, 15h, 15h, 18h,	25h
		.DB	   2, 14h, 14h, 26h,	27h
		.DB	   6, 14h, 14h, 28h,	37h
		.DB	   2, 12h, 13h, 38h,	39h
		.DB	   6, 12h, 12h, 26h,	37h
		.DB	   2, 12h, 12h, 24h,	25h
		.DB	   6, 13h, 13h, 1Ah,	23h
		.DB	   2, 12h, 12h, 18h,	19h
		.DB	   6, 12h, 12h, 0Ch,	17h
		.DB	   2, 10h, 12h, 0Ah,	0Bh
		.DB	   6, 10h, 10h, 0Ch,	19h
		.DB	   2, 10h, 10h, 1Ah,	1Bh
		.DB	   6, 11h, 11h, 1Ch,	21h
		.DB	   2, 10h, 10h, 22h,	23h
		.DB	   6, 10h, 10h, 24h,	37h
		.DB	   2,   2, 10h, 38h,	39h
		.DB	   6, 0Eh, 0Eh, 36h,	37h
		.DB	 0Bh, 0Eh, 0Eh, 34h,	35h
		.DB	   6,   2,	2, 24h,	37h
		.DB	   6,   3,	3, 1Ch,	1Fh
		.DB	   2,   3,	4, 20h,	21h
		.DB	   2,   5,	5, 1Eh,	1Fh
		.DB	   2,   6,	7, 1Ch,	1Dh
		.DB	   2,   8,	8, 1Eh,	1Fh
		.DB	   2,   9, 0Ah, 20h,	21h
		.DB	   2, 0Bh, 0Dh, 22h,	23h
		.DB	 0Bh, 0Eh, 0Eh, 24h,	25h
		.DB	   6, 0Eh, 0Eh, 26h,	2Fh
		.DB	   2, 0Ch, 0Eh, 30h,	31h
		.DB	   6, 0Ch, 0Ch, 28h,	2Fh
		.DB	   2, 0Ah, 0Ch, 26h,	27h
		.DB	   6, 0Ah, 0Ah, 28h,	2Fh
		.DB	   2,   8, 0Ah, 30h,	31h
		.DB	   6,   8,	8, 28h,	2Fh
		.DB	   2,   6,	8, 26h,	27h
		.DB	   6,   6,	6, 28h,	31h
		.DB	   2,   5,	6, 32h,	33h
		.DB	   2,   4,	4, 30h,	31h
		.DB	   6,   4,	4, 28h,	2Fh
		.DB	   7,   4,	4, 27h,	27h
		.DB	   7,   8,	8, 34h,	34h
		.DB	   7, 0Ah, 0Ah, 34h,	34h
		.DB	   7, 0Ch, 0Ch, 34h,	34h
		.DB	   2, 0Fh, 0Fh, 1Eh,	1Fh
		.DB	   2, 0Eh, 0Eh, 1Ch,	1Dh
		.DB	   2, 0Eh, 0Eh, 20h,	21h
		.DB	   6, 0Eh, 0Eh, 0Eh,	1Bh
		.DB	 0Bh, 0Eh, 0Eh, 0Ch,	0Dh
		.DB	   7, 0Dh, 0Dh, 0Ch,	15h
		.DB	   6, 0Dh, 0Dh, 18h,	1Bh
		.DB	 0Bh, 0Ch, 0Ch, 0Ah,	0Bh
		.DB	   6, 0Ch, 0Ch, 0Ch,	15h
		.DB	   7, 0Bh, 0Bh, 0Ah,	15h
		.DB	   7, 0Ch, 0Ch, 18h,	19h
		.DB	   2, 0Bh, 0Ch, 1Ah,	1Bh
		.DB	   2, 0Ch, 0Ch, 1Eh,	1Fh
		.DB	   2, 0Bh, 0Bh, 1Ch,	1Dh
		.DB	   2, 0Ah, 0Ah, 18h,	19h
		.DB	   2,   9,	9, 16h,	17h
		.DB	   2,   8,	8, 14h,	15h
		.DB	   2,   7,	7, 12h,	13h
		.DB	   2,   6,	6, 10h,	11h
		.DB	   2,   5,	5, 0Eh,	0Fh
		.DB	   2,   4,	4, 0Ch,	0Dh
		.DB	   2,   3,	3, 0Ah,	0Bh
		.DB	   2,   1,	2,   9,	  9
		.DB	 0Bh,   4,	5,   6,	  9
		.DB	 0Ah,   6,	6,   8,	  8
		.DB	   2,   7, 0Dh,   6,	  7
		.DB	 0Bh,   7,	7,   8,	  9
		.DB	   6,   7,	7, 0Ah,	11h
		.DB	   7,   9,	9,   8,	  9
		.DB	 0Bh, 0Ah, 0Ah,   8,	  9
		.DB	   7, 0Dh, 0Dh,   8,	  9
		.DB	 0Bh, 0Eh, 0Eh,   8,	  9
		.DB	   7,   2,	2, 1Ch,	1Dh
		.DB	   8,   9,	9,   9,	  9
		.DB	   0
;		tLevelAttr < 10h,    4,	   1,  0Bh, 0, 0, 0, 0,	0, 0,	 1, 0,	  9>
		.DB	10h,    4,	   1,  0Bh, 0, 0, 0, 0,	0, 0,	 1, 0,	  9

Level12:	.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01E8o
		.DB	   1, 15h, 17h,   4,	3Fh
		.DB	   1,   1, 14h, 3Ah,	3Fh
		.DB	   5, 16h, 16h,   4,	39h
		.DB	   6, 15h, 15h, 0Ah,	35h
		.DB	   6,   3,	3,   5,	1Dh
		.DB	   2,   3, 14h,   4,	  4
		.DB	   2,   1, 14h, 39h,	39h
		.DB	   1, 14h, 14h,   8,	  9
		.DB	   1, 13h, 13h, 36h,	38h
		.DB	 0Ah, 14h, 14h, 36h,	36h
		.DB	 0Bh,   3,	4, 1Eh,	1Fh
		.DB	 0Bh,   5,	5, 1Ah,	23h
		.DB	 0Bh,   6,	6, 18h,	1Dh
		.DB	 0Bh,   6,	6, 20h,	25h
		.DB	 0Bh,   7,	7, 1Ch,	21h
		.DB	 0Bh,   8,	8, 18h,	25h
		.DB	 0Bh,   9,	9, 16h,	1Bh
		.DB	 0Bh,   9,	9, 22h,	27h
		.DB	 0Bh, 0Ah, 0Ah, 1Ah,	23h
		.DB	 0Bh, 0Bh, 0Bh, 18h,	25h
		.DB	 0Bh, 0Ch, 0Ch, 16h,	1Bh
		.DB	 0Bh, 0Ch, 0Ch, 22h,	27h
		.DB	 0Bh, 0Dh, 0Dh, 1Ah,	23h
		.DB	 0Bh, 0Eh, 0Eh, 16h,	27h
		.DB	 0Bh, 0Fh, 0Fh, 14h,	1Bh
		.DB	 0Bh, 0Fh, 0Fh, 22h,	29h
		.DB	 0Bh, 10h, 10h, 1Ah,	23h
		.DB	 0Bh, 11h, 11h, 14h,	29h
		.DB	 0Bh, 12h, 12h, 12h,	1Bh
		.DB	 0Bh, 12h, 12h, 22h,	2Bh
		.DB	 0Bh, 13h, 14h, 18h,	19h
		.DB	 0Bh, 13h, 14h, 24h,	25h
		.DB	 0Bh, 15h, 16h, 12h,	2Bh
		.DB	   7,   7,	7, 1Eh,	1Fh
		.DB	   7, 0Ah, 0Ah, 1Ch,	21h
		.DB	   7, 0Dh, 0Dh, 1Ch,	21h
		.DB	   7, 10h, 10h, 1Ch,	21h
		.DB	   7, 14h, 14h, 1Ch,	21h
		.DB	   2,   8, 14h, 1Eh,	1Fh
		.DB	   8, 14h, 14h, 1Ch,	1Ch
		.DB	   0
;		tLevelAttr <14h, 7, 12h, 1Ch, 12h, 21h,	0, 0, 0, 0, 2, 0, 39h>
		.DB	14h, 7, 12h, 1Ch, 12h, 21h,	0, 0, 0, 0, 2, 0, 39h

Level13:	.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01EAo
		.DB	   1, 17h, 17h,   4,	3Fh
		.DB	   1,   1, 16h, 3Ch,	3Fh
		.DB	   1,   1,	1,   4,	13h
		.DB	   1,   1,	1, 16h,	2Bh
		.DB	   1,   1,	1, 2Eh,	3Bh
		.DB	 0Bh, 13h, 16h, 14h,	2Dh
		.DB	   5, 13h, 13h, 0Ah,	13h
		.DB	   5, 13h, 13h, 1Ah,	27h
		.DB	   5, 13h, 13h, 2Eh,	37h
		.DB	 1Ah, 14h, 16h, 0Ah,	13h
		.DB	 1Ah, 14h, 16h, 1Ah,	27h
		.DB	 1Ah, 14h, 16h, 2Eh,	3Bh
		.DB	   1, 12h, 13h,   4,	  5
		.DB	   1, 12h, 16h,   8,	  9
		.DB	   1, 16h, 16h,   4,	  7
		.DB	   2, 12h, 15h,   6,	  7
		.DB	   6,   4,	4, 0Ch,	35h
		.DB	   6,   6,	6, 0Ch,	1Bh
		.DB	   6,   6,	6, 26h,	35h
		.DB	   6,   8,	8, 0Ch,	35h
		.DB	   6, 0Ah, 0Ah, 0Ch,	13h
		.DB	   6, 0Ch, 0Ch, 0Ch,	13h
		.DB	   6, 0Eh, 0Eh, 0Ch,	13h
		.DB	   6, 10h, 10h, 0Ch,	13h
		.DB	   6, 12h, 12h, 0Ch,	0Fh
		.DB	   6, 0Ah, 0Ah, 2Eh,	35h
		.DB	   6, 0Ch, 0Ch, 2Eh,	35h
		.DB	   6, 0Eh, 0Eh, 2Eh,	35h
		.DB	   6, 10h, 10h, 2Eh,	35h
		.DB	   6, 12h, 12h, 32h,	35h
		.DB	 0Bh, 0Ah, 0Ah, 1Ah,	27h
		.DB	   6, 0Ah, 0Ah, 1Ch,	25h
		.DB	   6, 0Ch, 0Ch, 20h,	23h
		.DB	   6, 0Eh, 0Eh, 1Eh,	21h
		.DB	   6, 0Fh, 0Fh, 1Ah,	1Bh
		.DB	   6, 0Fh, 0Fh, 26h,	27h
		.DB	   6, 10h, 10h, 20h,	23h
		.DB	   6, 12h, 12h, 1Ah,	21h
		.DB	   6, 12h, 12h, 26h,	27h
		.DB	 0Bh,   4,	5, 20h,	21h
		.DB	 0Bh,   6,	7, 1Eh,	1Fh
		.DB	 0Bh,   6,	7, 22h,	23h
		.DB	 0Bh,   8,	9, 1Ch,	1Dh
		.DB	 0Bh,   8,	9, 24h,	25h
		.DB	 0Bh, 0Ch, 0Dh, 28h,	29h
		.DB	 0Bh, 0Ch, 0Dh, 18h,	19h
		.DB	 0Bh, 0Eh, 0Eh, 16h,	17h
		.DB	 0Bh, 0Eh, 0Eh, 2Ah,	2Bh
		.DB	 0Bh, 10h, 10h, 14h,	19h
		.DB	 0Bh, 10h, 10h, 28h,	2Dh
		.DB	 0Bh, 12h, 12h, 14h,	15h
		.DB	 0Bh, 12h, 12h, 2Ch,	2Dh
		.DB	   2,   4, 12h, 0Ah,	0Bh
		.DB	   2,   4, 12h, 10h,	11h
		.DB	   2,   4, 0Dh, 16h,	17h
		.DB	   2,   4,	7, 1Ch,	1Dh
		.DB	   2,   4,	7, 24h,	25h
		.DB	   2,   4, 0Dh, 2Ah,	2Bh
		.DB	   2,   4, 12h, 30h,	31h
		.DB	   2,   4, 12h, 36h,	37h
		.DB	   2, 0Ch, 12h, 1Ch,	1Dh
		.DB	   2, 0Ch, 12h, 24h,	25h
		.DB	   1,   2, 14h, 38h,	3Bh
		.DB	 0Eh, 11h, 11h, 38h,	3Bh
		.DB	   2,   1, 11h, 3Bh,	3Bh
		.DB	 0Ah, 11h, 11h, 39h,	39h
		.DB	   7,   7,	7, 20h,	21h
		.DB	   7,   9,	9, 20h,	21h
		.DB	   7, 0Bh, 0Bh, 20h,	21h
		.DB	   7, 0Dh, 0Dh, 20h,	21h
		.DB	   7, 0Fh, 0Fh, 20h,	21h
		.DB	   7, 11h, 11h, 20h,	21h
		.DB	   8, 0Fh, 0Fh, 20h,	20h
		.DB	   3, 0Fh, 0Fh, 16h,	16h
		.DB	   4, 0Fh, 0Fh, 2Bh,	2Bh
		.DB	   0
;		tLevelAttr <14h, 4, 1, 14h, 1, 2Dh, 0, 0, 0, 0,	2, 0, 3Bh>
		.DB	14h, 4, 1, 14h, 1, 2Dh, 0, 0, 0, 0,	2, 0, 3Bh

Level14:	.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01ECo
		.DB	   1, 16h, 17h,   4,	3Fh
		.DB	   1,   1, 15h, 3Ch,	3Fh
		.DB	   5, 16h, 16h, 0Eh,	33h
		.DB	   2,   4, 15h,   6,	  7
		.DB	   6,   4,	4,   8,	21h
		.DB	 0Bh,   2,	2, 20h,	21h
		.DB	 0Bh,   4,	4, 1Eh,	1Fh
		.DB	 0Bh,   4,	4, 22h,	23h
		.DB	 0Bh,   6,	6, 1Ch,	25h
		.DB	   6,   6,	6, 20h,	21h
		.DB	 0Bh,   8,	8, 1Ah,	1Bh
		.DB	 0Bh,   8,	8, 1Eh,	23h
		.DB	 0Bh,   8,	8, 26h,	27h
		.DB	 0Bh, 0Ah, 0Ah, 18h,	1Bh
		.DB	 0Bh, 0Ah, 0Ah, 1Eh,	23h
		.DB	 0Bh, 0Ah, 0Ah, 26h,	29h
		.DB	 0Bh, 0Ch, 0Ch, 16h,	19h
		.DB	 0Bh, 0Ch, 0Ch, 1Ch,	25h
		.DB	 0Bh, 0Ch, 0Ch, 28h,	2Bh
		.DB	 0Bh, 0Eh, 0Eh, 14h,	17h
		.DB	 0Bh, 0Eh, 0Eh, 1Ah,	27h
		.DB	 0Bh, 0Eh, 0Eh, 2Ah,	2Dh
		.DB	 0Bh, 10h, 10h, 12h,	15h
		.DB	 0Bh, 10h, 10h, 18h,	29h
		.DB	 0Bh, 10h, 10h, 2Ch,	2Fh
		.DB	 0Bh, 12h, 12h, 10h,	13h
		.DB	 0Bh, 12h, 12h, 16h,	2Bh
		.DB	 0Bh, 12h, 12h, 2Eh,	31h
		.DB	 0Bh, 14h, 14h, 0Eh,	33h
		.DB	   7,   5,	5, 1Eh,	23h
		.DB	   7,   7,	7, 1Eh,	23h
		.DB	   7,   9,	9, 1Eh,	23h
		.DB	   7, 0Bh, 0Bh, 1Eh,	23h
		.DB	   7, 0Dh, 0Dh, 1Eh,	23h
		.DB	   7, 0Fh, 0Fh, 1Eh,	23h
		.DB	   7, 11h, 11h, 1Eh,	23h
		.DB	   7, 13h, 13h, 1Eh,	23h
		.DB	 0Eh,   7, 14h, 20h,	21h
		.DB	   1, 14h, 14h, 38h,	3Bh
		.DB	   2,   1, 15h, 3Bh,	3Bh
		.DB	 0Ah, 15h, 15h, 39h,	39h
		.DB	 0Eh,   5,	5, 20h,	21h
		.DB	   8,   9,	9, 23h,	23h
		.DB	   0
;		tLevelAttr <14h, 4, 1, 1Ch, 1, 25h, 0, 0, 0, 0,	2, 0, 3Bh>
		.DB	14h, 4, 1, 1Ch, 1, 25h, 0, 0, 0, 0,	2, 0, 3Bh

Level15:	.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01EEo
		.DB	   1, 17h, 17h,   4,	3Fh
		.DB	   1,   1, 16h, 3Ah,	3Fh
		.DB	 0Eh, 11h, 11h, 3Ah,	3Ch
		.DB	   5, 13h, 13h,   4,	39h
		.DB	 1Bh, 14h, 16h,   4,	39h
		.DB	   2,   2, 11h,   2,	  3
		.DB	   6,   3,	3,   4,	37h
		.DB	   2,   3,	8, 38h,	39h
		.DB	   6,   7,	7,   8,	37h
		.DB	   7,   9, 11h, 20h,	21h
		.DB	   6, 0Ch, 0Ch,   6,	39h
		.DB	   6,   9, 0Ah, 30h,	37h
		.DB	   2,   9,	9, 30h,	31h
		.DB	   2, 0Ah, 0Bh, 38h,	39h
		.DB	   6,   9, 0Ah,   8,	11h
		.DB	   2,   7,	8,   6,	  7
		.DB	   2,   9,	9, 10h,	11h
		.DB	   2, 0Ah, 0Bh,   6,	  7
		.DB	   6, 12h, 12h,   4,	13h
		.DB	   6, 12h, 12h, 2Eh,	39h
		.DB	 0Bh,   4,	5, 20h,	21h
		.DB	 0Bh,   6,	7, 1Eh,	23h
		.DB	 0Bh,   8,	9, 1Ch,	1Fh
		.DB	 0Bh, 0Ah, 0Bh, 1Ah,	1Dh
		.DB	 0Bh, 0Ch, 0Dh, 18h,	1Bh
		.DB	 0Bh, 0Eh, 0Fh, 16h,	19h
		.DB	 0Bh, 10h, 10h, 14h,	17h
		.DB	 0Bh, 11h, 13h, 14h,	15h
		.DB	 0Bh, 13h, 13h, 16h,	19h
		.DB	 0Bh, 12h, 12h, 18h,	19h
		.DB	 0Bh,   8,	9, 22h,	25h
		.DB	 0Bh, 0Ah, 0Bh, 24h,	27h
		.DB	 0Bh, 0Ch, 0Dh, 26h,	29h
		.DB	 0Bh, 0Eh, 0Fh, 28h,	2Bh
		.DB	 0Bh, 10h, 10h, 2Ah,	2Bh
		.DB	 0Bh, 11h, 13h, 2Ch,	2Dh
		.DB	 0Bh, 13h, 13h, 28h,	2Bh
		.DB	 0Bh, 12h, 12h, 28h,	29h
		.DB	   6, 0Ah, 0Ah, 1Eh,	23h
		.DB	   6, 0Eh, 0Eh, 1Ah,	21h
		.DB	   6, 0Eh, 0Eh, 26h,	27h
		.DB	   6, 10h, 10h, 1Ah,	1Bh
		.DB	   6, 10h, 10h, 20h,	27h
		.DB	   6, 12h, 12h, 1Ah,	21h
		.DB	   6, 12h, 12h, 26h,	27h
		.DB	   2, 0Eh, 12h, 1Ch,	1Dh
		.DB	   2, 0Eh, 12h, 24h,	25h
		.DB	 0Ah, 11h, 11h, 3Bh,	3Bh
		.DB	   2,   1, 11h, 3Dh,	3Dh
		.DB	   8, 11h, 11h, 21h,	21h
		.DB	   1,   1,	1,   4,	1Dh
		.DB	   1,   1,	1, 20h,	21h
		.DB	   1,   1,	1, 24h,	3Ah
		.DB	   0
;		tLevelAttr <2, 2, 1, 1Fh, 1, 22h, 0, 0,	0, 0, 2, 0, 3Dh>
		.DB	2, 2, 1, 1Fh, 1, 22h, 0, 0,	0, 0, 2, 0, 3Dh

Level16:	.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01F0o
		.DB	   1, 16h, 17h,   4,	3Fh
		.DB	   1,   1, 17h, 3Ch,	3Fh
		.DB	   2, 13h, 15h,   9,	  9
		.DB	   2,   4, 12h, 0Ah,	0Ah
		.DB	   6,   4,	4, 0Bh,	1Dh
		.DB	 0Bh,   2,	2, 20h,	21h
		.DB	 0Bh,   4,	4, 1Eh,	23h
		.DB	 0Bh,   6,	6, 1Ch,	25h
		.DB	   6,   6,	6, 1Eh,	1Fh
		.DB	   6,   6,	6, 22h,	23h
		.DB	   7,   5,	5, 20h,	21h
		.DB	 0Bh,   8,	8, 1Ah,	1Bh
		.DB	 0Bh,   8,	8, 1Eh,	23h
		.DB	 0Bh,   8,	8, 26h,	27h
		.DB	   7,   9,	9, 1Ch,	1Dh
		.DB	   7,   9,	9, 24h,	25h
		.DB	 0Bh, 0Ah, 0Ah, 18h,	19h
		.DB	 0Bh, 0Ah, 0Ah, 1Ch,	1Fh
		.DB	 0Bh, 0Ah, 0Ah, 22h,	25h
		.DB	 0Bh, 0Ah, 0Ah, 28h,	29h
		.DB	   7, 0Bh, 0Bh, 1Ah,	1Bh
		.DB	   7, 0Bh, 0Bh, 26h,	27h
		.DB	 0Bh, 0Ch, 0Ch, 16h,	17h
		.DB	   6, 0Ch, 0Ch, 1Ah,	1Bh
		.DB	   1, 0Ch, 0Eh, 1Ch,	1Dh
		.DB	   1, 0Eh, 0Eh, 1Eh,	25h
		.DB	   1, 0Ch, 0Dh, 24h,	25h
		.DB	 0Bh, 0Ch, 0Ch, 26h,	2Bh
		.DB	   6, 0Ch, 0Ch, 28h,	29h
		.DB	   2, 0Eh, 0Eh, 18h,	19h
		.DB	 0Bh, 0Eh, 0Eh, 14h,	15h
		.DB	   5, 0Dh, 0Dh, 1Eh,	23h
		.DB	   2, 0Eh, 0Eh, 28h,	29h
		.DB	 0Bh, 0Eh, 0Eh, 2Ch,	2Dh
		.DB	 0Bh, 10h, 10h, 12h,	13h
		.DB	 0Bh, 10h, 10h, 16h,	1Fh
		.DB	   6, 10h, 10h, 18h,	1Bh
		.DB	 0Bh, 10h, 10h, 22h,	2Bh
		.DB	 0Bh, 10h, 10h, 2Eh,	2Fh
		.DB	 0Bh, 12h, 12h, 10h,	17h
		.DB	   6, 12h, 12h, 12h,	13h
		.DB	 0Bh, 12h, 12h, 1Ah,	1Fh
		.DB	   6, 12h, 12h, 20h,	21h
		.DB	 0Bh, 12h, 12h, 24h,	27h
		.DB	 0Bh, 12h, 12h, 2Ah,	31h
		.DB	   6, 12h, 12h, 2Eh,	2Fh
		.DB	 0Bh, 14h, 14h, 0Eh,	15h
		.DB	 0Bh, 14h, 14h, 18h,	19h
		.DB	 0Bh, 14h, 14h, 1Ch,	1Fh
		.DB	 0Bh, 14h, 14h, 22h,	29h
		.DB	 0Bh, 14h, 14h, 2Ch,	2Fh
		.DB	 0Bh, 14h, 14h, 32h,	33h
		.DB	   1, 14h, 14h, 38h,	3Bh
		.DB	 0Ah, 15h, 15h, 39h,	39h
		.DB	   2,   1, 15h, 3Bh,	3Bh
		.DB	   7, 0Fh, 0Fh, 16h,	17h
		.DB	   4, 0Fh, 0Fh, 1Ah,	1Bh
		.DB	   7, 0Fh, 0Fh, 2Ah,	2Bh
		.DB	   7, 11h, 11h, 14h,	15h
		.DB	   7, 11h, 11h, 1Eh,	1Fh
		.DB	   7, 11h, 11h, 2Ch,	2Dh
		.DB	   3, 13h, 13h, 10h,	10h
		.DB	   7, 13h, 13h, 22h,	23h
		.DB	   8, 11h, 11h, 1Eh,	1Eh
		.DB	   0
;		tLevelAttr <15h, 4, 1, 1Ah, 1, 27h, 0, 0, 0, 0,	2, 0, 3Bh>
		.DB	15h, 4, 1, 1Ah, 1, 27h, 0, 0, 0, 0,	2, 0, 3Bh

Level17:	.DB	   1,   1, 17h,   0,	  3 ; DATA XREF: ROM:01F2o
		.DB	   1, 16h, 17h,   4,	3Fh
		.DB	   1,   1, 15h, 3Ch,	3Fh
		.DB	   5, 16h, 16h, 10h,	3Bh
		.DB	   6, 15h, 15h,   8,	3Bh
		.DB	   2,   3, 15h,   4,	  5
		.DB	   1,   4, 14h,   6,	  7
		.DB	   1, 14h, 15h, 0Eh,	0Fh
		.DB	   6,   3,	3,   6,	0Bh
		.DB	   6,   2,	2, 12h,	2Bh
		.DB	   6,   3,	3, 0Eh,	29h
		.DB	   6,   4,	4, 14h,	29h
		.DB	   6,   5,	5, 0Ah,	25h
		.DB	   2,   1,	2, 0Eh,	0Eh
		.DB	   2,   2,	2, 28h,	29h
		.DB	   6,   7,	7, 0Ah,	19h
		.DB	   6,   7,	7, 20h,	25h
		.DB	   2,   5,	6,   8,	  9
		.DB	   2,   8,	9,   8,	  9
		.DB	   6,   9,	9, 0Ah,	0Dh
		.DB	   1,   6,	9, 0Eh,	0Fh
		.DB	   2,   7,	9, 10h,	11h
		.DB	   6, 0Ah, 0Ah, 10h,	13h
		.DB	   1, 0Ch, 0Ch, 0Ch,	0Fh
		.DB	   2, 0Dh, 0Dh, 0Ah,	0Bh
		.DB	   1, 0Eh, 0Fh,   8,	0Bh
		.DB	   5, 0Eh, 0Eh,   8,	  9
		.DB	   2, 11h, 14h,   8,	  9
		.DB	   1, 11h, 13h, 0Ah,	0Bh
		.DB	   2, 0Eh, 10h, 0Ch,	0Dh
		.DB	   1, 11h, 11h, 0Ch,	0Fh
		.DB	   1, 0Eh, 10h, 0Eh,	0Fh
		.DB	   6, 0Eh, 0Eh, 10h,	17h
		.DB	   1, 0Fh, 0Fh, 10h,	19h
		.DB	   6, 0Fh, 0Fh, 12h,	13h
		.DB	   2, 0Ah, 0Dh, 14h,	15h
		.DB	   1,   9, 0Dh, 16h,	17h
		.DB	   2,   9, 0Eh, 18h,	19h
		.DB	   2,   7,	7, 1Eh,	1Fh
		.DB	   2,   7,	7, 26h,	27h
		.DB	   6,   9,	9, 1Ah,	21h
		.DB	   2,   9,	9, 1Eh,	1Fh
		.DB	   2,   4,	9, 2Ah,	2Bh
		.DB	   6, 0Ah, 0Ah, 24h,	2Bh
		.DB	   2, 0Ah, 0Eh, 22h,	23h
		.DB	 0Bh, 0Bh, 0Bh, 1Ch,	1Dh
		.DB	 0Bh, 0Dh, 0Dh, 1Ch,	1Dh
		.DB	 0Bh, 0Fh, 0Fh, 20h,	23h
		.DB	   6, 0Fh, 0Fh, 1Eh,	1Fh
		.DB	   2, 0Fh, 0Fh, 1Ch,	1Dh
		.DB	   6, 10h, 10h, 1Eh,	23h
		.DB	   1, 10h, 10h, 1Ch,	1Dh
		.DB	   2, 10h, 11h, 1Ah,	1Bh
		.DB	   1, 11h, 11h, 1Ch,	27h
		.DB	   2, 0Ch, 0Eh, 26h,	27h
		.DB	   6, 11h, 11h, 24h,	25h
		.DB	   6, 0Ch, 0Ch, 28h,	29h
		.DB	   1, 0Fh, 0Fh, 26h,	27h
		.DB	   6, 0Fh, 0Fh, 28h,	2Fh
		.DB	   6, 11h, 11h, 28h,	2Fh
		.DB	   6, 12h, 12h, 12h,	19h
		.DB	   1, 13h, 13h, 12h,	27h
		.DB	   6, 13h, 13h, 0Eh,	11h
		.DB	   6, 13h, 13h, 14h,	19h
		.DB	   6, 13h, 13h, 24h,	25h
		.DB	   6, 13h, 13h, 28h,	29h
		.DB	   2, 13h, 14h, 1Ch,	1Dh
		.DB	 0Bh, 0Dh, 0Dh, 2Ah,	2Bh
		.DB	 0Bh, 0Fh, 0Fh, 2Ah,	2Bh
		.DB	 0Bh, 11h, 11h, 2Ah,	2Bh
		.DB	 0Bh, 13h, 13h, 2Ah,	2Bh
		.DB	   2, 11h, 11h, 30h,	31h
		.DB	 0Bh, 11h, 11h, 32h,	33h
		.DB	 0Bh, 11h, 11h, 36h,	37h
		.DB	   2, 11h, 12h, 38h,	39h
		.DB	 0Bh, 13h, 13h, 36h,	39h
		.DB	   6, 13h, 13h, 34h,	35h
		.DB	   2, 13h, 14h, 32h,	33h
		.DB	   7,   2, 0Eh, 34h,	35h
		.DB	 0Bh,   3,	3, 30h,	37h
		.DB	 0Bh,   5,	5, 32h,	37h
		.DB	 0Bh,   9,	9, 32h,	37h
		.DB	 0Bh,   7,	7, 32h,	37h
		.DB	 0Bh, 0Bh, 0Bh, 32h,	37h
		.DB	 0Bh, 0Dh, 0Dh, 32h,	37h
		.DB	 0Bh, 0Fh, 0Fh, 30h,	37h
		.DB	   2,   2,	3, 2Eh,	2Fh
		.DB	   2,   3,	3, 34h,	35h
		.DB	   2,   3,	4, 38h,	39h
		.DB	   2,   5,	6, 30h,	31h
		.DB	   2,   5,	5, 34h,	35h
		.DB	   2,   7,	7, 34h,	35h
		.DB	   2,   7,	8, 38h,	39h
		.DB	   2,   9,	9, 34h,	35h
		.DB	   2,   9, 0Ah, 30h,	31h
		.DB	   2, 0Bh, 0Bh, 34h,	35h
		.DB	   2, 0Bh, 0Ch, 38h,	39h
		.DB	   2, 0Dh, 0Dh, 34h,	35h
		.DB	   2, 0Dh, 0Eh, 30h,	31h
		.DB	   2, 0Fh, 0Fh, 34h,	35h
		.DB	   1,   1,	1, 32h,	33h
		.DB	   1,   1,	1, 36h,	3Bh
		.DB	   1,   2,	2, 2Ch,	2Dh
		.DB	   7,   2,	2, 0Ah,	0Bh
		.DB	   7,   2,	2, 10h,	11h
		.DB	   7,   1,	1, 12h,	13h
		.DB	   7,   6,	6, 0Ch,	0Dh
		.DB	   7,   8,	8, 0Ch,	0Dh
		.DB	   7,   6,	6, 18h,	19h
		.DB	   7,   6,	6, 1Eh,	1Fh
		.DB	   7,   6,	6, 26h,	27h
		.DB	   7,   8,	8, 1Ch,	1Dh
		.DB	   7,   8,	8, 20h,	21h
		.DB	   7, 0Ah, 0Ah, 1Ch,	1Dh
		.DB	   7, 0Ch, 0Ch, 1Ch,	1Dh
		.DB	   7, 0Bh, 0Bh, 0Eh,	0Fh
		.DB	   7, 0Ch, 0Ch, 0Ah,	0Bh
		.DB	   7, 0Ch, 0Ch, 2Ah,	2Bh
		.DB	   7, 0Eh, 0Eh, 2Ah,	2Bh
		.DB	   7, 10h, 10h, 2Ah,	2Bh
		.DB	   7, 12h, 12h, 2Ah,	2Bh
		.DB	   7, 12h, 12h, 1Ch,	1Dh
		.DB	   7, 12h, 12h, 20h,	21h
		.DB	   7, 14h, 14h, 10h,	11h
		.DB	   8, 12h, 12h, 1Ch,	1Ch
		.DB	   3, 11h, 11h, 12h,	13h
		.DB	   4, 12h, 12h, 1Ah,	1Bh
		.DB	   4, 12h, 12h, 1Eh,	1Eh
		.DB	   3, 12h, 12h, 32h,	33h
		.DB	   9,   2,	2, 33h,	33h
		.DB	   0
;		tLevelAttr <15h, 6, 0, 11h, 0, 34h, 0, 0, 0, 0,	2, 0, 0Eh>
		.DB	15h, 6, 0, 11h, 0, 34h, 0, 0, 0, 0,	2, 0, 0Eh

Level18:	.DB	   1,   1, 17h,   0,	  5 ; DATA XREF: ROM:01F4o
		.DB	   1, 16h, 17h,   0,	3Fh
		.DB	   1,   1, 17h, 3Ch,	3Fh
		.DB	   5, 16h, 16h,   6,	  9
		.DB	   5, 16h, 16h, 38h,	3Bh
		.DB	   1, 0Eh, 14h, 0Ch,	35h
		.DB	   2, 0Eh, 15h, 0Ah,	0Bh
		.DB	   2,   4, 0Eh,   6,	  7
		.DB	   6, 0Fh, 0Fh,   6,	  9
		.DB	   5, 0Fh, 0Fh, 0Eh,	1Fh
		.DB	   5, 0Fh, 0Fh, 22h,	33h
		.DB	 0Bh,   4,	8,   8,	11h
		.DB	   2,   4,	4, 10h,	11h
		.DB	   1,   5,	7,   8,	  9
		.DB	   1,   5,	6, 10h,	11h
		.DB	   7,   5,	7, 0Ah,	0Fh
		.DB	   1,   9, 0Ch,   8,	  9
		.DB	   6,   9,	9, 0Ah,	0Fh
		.DB	   1,   9, 0Ch, 10h,	11h
		.DB	   7, 0Ah, 0Ch, 0Ah,	0Fh
		.DB	   6,   8,	8, 12h,	1Bh
		.DB	 0Bh,   9,	9, 14h,	15h
		.DB	   1, 0Ah, 0Dh, 14h,	15h
		.DB	   2, 0Ah, 0Dh, 16h,	17h
		.DB	   1, 0Dh, 0Dh, 18h,	1Bh
		.DB	   6, 0Eh, 0Eh, 1Eh,	23h
		.DB	   2,   1, 0Eh, 20h,	21h
		.DB	   6,   8,	8, 26h,	2Fh
		.DB	 0Bh,   9,	9, 2Ch,	2Dh
		.DB	   2, 0Ah, 0Dh, 2Ah,	2Bh
		.DB	   1, 0Dh, 0Dh, 26h,	29h
		.DB	   1, 0Ah, 0Dh, 2Ch,	2Dh
		.DB	 0Bh,   4,	8, 30h,	39h
		.DB	   2,   4,	4, 30h,	31h
		.DB	   1,   5,	6, 30h,	31h
		.DB	   1,   5,	7, 38h,	39h
		.DB	   7,   5,	7, 32h,	37h
		.DB	   2,   4, 0Eh, 3Ah,	3Bh
		.DB	   6, 0Fh, 0Fh, 38h,	3Bh
		.DB	   1,   9, 0Ch, 30h,	39h
		.DB	   6,   9,	9, 32h,	37h
		.DB	   7, 0Ah, 0Ch, 32h,	37h
		.DB	   2, 0Eh, 15h, 36h,	37h
		.DB	 1Bh, 10h, 12h, 0Eh,	33h
		.DB	   1,   1,	1,   6,	1Fh
		.DB	   1,   1,	1, 21h,	3Bh
		.DB	   0
;		tLevelAttr <15h, 20h, 2, 18h, 2, 29h, 0, 0, 0, 0, 2, 0,	20h>
		.DB	15h, 20h, 2, 18h, 2, 29h, 0, 0, 0, 0, 2, 0, 20h
; end of 'ROM'

ShutBufPtr:	.DB	100
vShutCounter:	.DB	0			; DATA XREF: sub_13A4+29r
ShutBuffer:
MapLine0:	= ShutBuffer + 512
		.end
